openapi: 3.0.3
info:
  title: App Secrets API
  description: API endpoints for managing app secret variables
  version: 1.0.0

servers:
  - url: http://localhost:3847/api
    description: Development server

paths:
  /apps/{appId}/secrets:
    get:
      summary: List all secrets for an app
      description: Returns all secret variables for the specified app. Values are included (frontend handles masking).
      operationId: listSecrets
      tags:
        - Secrets
      security:
        - bearerAuth: []
      parameters:
        - name: appId
          in: path
          required: true
          description: The app's unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of secrets
          content:
            application/json:
              schema:
                type: object
                properties:
                  secrets:
                    type: array
                    items:
                      $ref: '#/components/schemas/AppSecret'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Create a new secret
      description: Creates a new secret variable for the specified app
      operationId: createSecret
      tags:
        - Secrets
      security:
        - bearerAuth: []
      parameters:
        - name: appId
          in: path
          required: true
          description: The app's unique identifier
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSecretRequest'
      responses:
        '201':
          description: Secret created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSecret'
        '400':
          description: Invalid request (validation error or duplicate key)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                duplicateKey:
                  summary: Duplicate key error
                  value:
                    statusCode: 400
                    message: "Secret with key 'API_KEY' already exists for this app"
                    error: "Bad Request"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /secrets/{secretId}:
    patch:
      summary: Update a secret
      description: Updates an existing secret's key and/or value
      operationId: updateSecret
      tags:
        - Secrets
      security:
        - bearerAuth: []
      parameters:
        - name: secretId
          in: path
          required: true
          description: The secret's unique identifier
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSecretRequest'
      responses:
        '200':
          description: Secret updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSecret'
        '400':
          description: Invalid request (validation error or duplicate key)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a secret
      description: Permanently deletes a secret variable
      operationId: deleteSecret
      tags:
        - Secrets
      security:
        - bearerAuth: []
      parameters:
        - name: secretId
          in: path
          required: true
          description: The secret's unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Secret deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AppSecret:
      type: object
      required:
        - id
        - appId
        - key
        - value
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        appId:
          type: string
          format: uuid
          description: Parent app identifier
          example: "660e8400-e29b-41d4-a716-446655440001"
        key:
          type: string
          minLength: 1
          maxLength: 256
          pattern: '^[A-Za-z_][A-Za-z0-9_]*$'
          description: Secret variable name (env var naming convention)
          example: "OPENAI_API_KEY"
        value:
          type: string
          description: Secret value
          example: "sk-proj-abc123..."
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2026-01-16T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-01-16T10:30:00Z"

    CreateSecretRequest:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
          minLength: 1
          maxLength: 256
          pattern: '^[A-Za-z_][A-Za-z0-9_]*$'
          description: Secret variable name
          example: "DATABASE_URL"
        value:
          type: string
          minLength: 1
          description: Secret value
          example: "postgresql://user:pass@localhost:5432/db"

    UpdateSecretRequest:
      type: object
      properties:
        key:
          type: string
          minLength: 1
          maxLength: 256
          pattern: '^[A-Za-z_][A-Za-z0-9_]*$'
          description: New secret variable name
          example: "NEW_API_KEY"
        value:
          type: string
          minLength: 1
          description: New secret value
          example: "new-secret-value"

    Error:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        message:
          type: string
          example: "Validation failed"
        error:
          type: string
          example: "Bad Request"

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            statusCode: 401
            message: "Unauthorized"
            error: "Unauthorized"

    Forbidden:
      description: User does not have access to this app
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            statusCode: 403
            message: "You do not have access to this app"
            error: "Forbidden"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            statusCode: 404
            message: "Secret not found"
            error: "Not Found"
