# Configuration for actions/labeler
# Labels PRs based on which files are changed

# Manifest package label
manifest:
  - changed-files:
      - any-glob-to-any-file: 'packages/manifest/**'

# Manifest UI package label
manifest UI:
  - changed-files:
      - any-glob-to-any-file: 'packages/manifest-ui/**'

# ui.manifest.build website label (subset of manifest-ui)
ui.manifest.build:
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/manifest-ui/app/**'
          - 'packages/manifest-ui/components/**'
          - 'packages/manifest-ui/lib/**'
          - 'packages/manifest-ui/public/**'
          - 'packages/manifest-ui/registry/**'
          - 'packages/manifest-ui/styles/**'
