openapi: 3.0.3
info:
  title: Call Flow API
  description: REST API for managing Call Flow end actions
  version: 1.0.0

servers:
  - url: /api
    description: Local development server

paths:
  /flows/{flowId}/call-flows:
    get:
      summary: List call flows for a flow
      operationId: listCallFlows
      tags:
        - CallFlows
      parameters:
        - $ref: '#/components/parameters/flowId'
      responses:
        '200':
          description: List of call flows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CallFlow'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Create a call flow
      operationId: createCallFlow
      tags:
        - CallFlows
      parameters:
        - $ref: '#/components/parameters/flowId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCallFlowRequest'
      responses:
        '201':
          description: Call flow created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallFlow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /flows/{flowId}/call-flows/reorder:
    post:
      summary: Reorder call flows
      operationId: reorderCallFlows
      tags:
        - CallFlows
      parameters:
        - $ref: '#/components/parameters/flowId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReorderCallFlowsRequest'
      responses:
        '200':
          description: Call flows reordered
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CallFlow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /call-flows/{callFlowId}:
    get:
      summary: Get a call flow by ID
      operationId: getCallFlow
      tags:
        - CallFlows
      parameters:
        - $ref: '#/components/parameters/callFlowId'
      responses:
        '200':
          description: Call flow details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallFlow'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update a call flow
      operationId: updateCallFlow
      tags:
        - CallFlows
      parameters:
        - $ref: '#/components/parameters/callFlowId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCallFlowRequest'
      responses:
        '200':
          description: Call flow updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallFlow'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a call flow
      operationId: deleteCallFlow
      tags:
        - CallFlows
      parameters:
        - $ref: '#/components/parameters/callFlowId'
      responses:
        '204':
          description: Call flow deleted
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    flowId:
      name: flowId
      in: path
      required: true
      description: UUID of the parent flow
      schema:
        type: string
        format: uuid

    callFlowId:
      name: callFlowId
      in: path
      required: true
      description: UUID of the call flow
      schema:
        type: string
        format: uuid

  schemas:
    CallFlow:
      type: object
      required:
        - id
        - flowId
        - targetFlowId
        - order
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier
        flowId:
          type: string
          format: uuid
          description: Parent flow ID
        targetFlowId:
          type: string
          format: uuid
          nullable: true
          description: Target flow to call (null if deleted)
        targetFlow:
          $ref: '#/components/schemas/FlowSummary'
          description: Target flow details (populated when available)
        order:
          type: integer
          minimum: 0
          description: Position among multiple call flows
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    FlowSummary:
      type: object
      description: Minimal flow info for display purposes
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        toolName:
          type: string

    CreateCallFlowRequest:
      type: object
      required:
        - targetFlowId
      properties:
        targetFlowId:
          type: string
          format: uuid
          description: Flow to call when this action executes

    UpdateCallFlowRequest:
      type: object
      properties:
        targetFlowId:
          type: string
          format: uuid
          description: New target flow (optional)

    ReorderCallFlowsRequest:
      type: object
      required:
        - orderedIds
      properties:
        orderedIds:
          type: array
          items:
            type: string
            format: uuid
          description: Call flow IDs in desired order

    Error:
      type: object
      required:
        - message
        - statusCode
      properties:
        message:
          type: string
        statusCode:
          type: integer
        error:
          type: string

  responses:
    BadRequest:
      description: Validation error or business rule violation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            mutualExclusivity:
              summary: Mutual exclusivity violation
              value:
                statusCode: 400
                message: "Cannot add call flows to a flow that has views"
                error: "Bad Request"
            selfReference:
              summary: Self-reference attempt
              value:
                statusCode: 400
                message: "A flow cannot call itself"
                error: "Bad Request"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            statusCode: 404
            message: "Flow not found"
            error: "Not Found"
