# Registry API Contract
# External API at https://ui.manifest.build/r/
# This documents the expected external API format for frontend consumption

openapi: 3.0.3
info:
  title: UI Registry API
  description: External registry API for UI components
  version: 1.0.0

servers:
  - url: https://ui.manifest.build/r
    description: Default registry server
  - url: '{customUrl}'
    description: Custom registry URL (via VITE_REGISTRY_URL)
    variables:
      customUrl:
        default: https://ui.manifest.build/r

paths:
  /registry.json:
    get:
      operationId: getRegistry
      summary: Get all registry items
      description: Returns the complete list of available UI components with metadata
      responses:
        '200':
          description: Registry list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistryResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /{componentName}.json:
    get:
      operationId: getComponentDetail
      summary: Get component details including source code
      description: Returns full component data including file contents
      parameters:
        - name: componentName
          in: path
          required: true
          description: Component identifier (e.g., "post-card")
          schema:
            type: string
      responses:
        '200':
          description: Component details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentDetail'
        '404':
          description: Component not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    RegistryResponse:
      type: object
      required:
        - items
      properties:
        $schema:
          type: string
          description: JSON Schema reference
        name:
          type: string
          description: Registry name
        homepage:
          type: string
          format: uri
          description: Registry homepage URL
        items:
          type: array
          items:
            $ref: '#/components/schemas/RegistryItem'

    RegistryItem:
      type: object
      required:
        - name
        - version
        - type
        - title
        - category
      properties:
        name:
          type: string
          description: Unique component identifier
          example: post-card
        version:
          type: string
          description: Semantic version
          example: '2.0.2'
        type:
          type: string
          description: Registry item type
          example: registry:block
        title:
          type: string
          description: Human-readable display name
          example: Post Card
        description:
          type: string
          description: Component description
          example: Display blog posts with rich formatting
        category:
          type: string
          description: Component category for grouping
          enum:
            - form
            - payment
            - list
            - blogging
            - messaging
            - events
            - miscellaneous
          example: blogging
        dependencies:
          type: array
          items:
            type: string
          description: NPM package dependencies
          example: ['lucide-react']
        registryDependencies:
          type: array
          items:
            type: string
          description: Dependencies on other registry items
          example: ['button']
        files:
          type: array
          items:
            $ref: '#/components/schemas/FileMetadata'
          description: File metadata (paths only, no content)

    FileMetadata:
      type: object
      required:
        - path
        - type
      properties:
        path:
          type: string
          description: File path within registry
          example: registry/blogging/post-card.tsx
        type:
          type: string
          description: File type classification
          example: registry:component

    ComponentDetail:
      allOf:
        - $ref: '#/components/schemas/RegistryItem'
        - type: object
          properties:
            $schema:
              type: string
              description: JSON Schema reference
            changelog:
              type: object
              additionalProperties:
                type: string
              description: Version history (version -> description)
            files:
              type: array
              items:
                $ref: '#/components/schemas/ComponentFile'
              description: Files with full source code

    ComponentFile:
      type: object
      required:
        - path
        - type
        - content
      properties:
        path:
          type: string
          description: File path within registry
          example: registry/blogging/post-card.tsx
        type:
          type: string
          description: File type classification
          example: registry:component
        content:
          type: string
          description: Full source code content

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
