# OpenAPI Contract: API Call Node
# Feature: 018-api-call-action
# Date: 2026-01-06
#
# This contract documents the existing Node API endpoints that will support
# the new ApiCall node type. No new endpoints are required.

openapi: 3.0.3
info:
  title: Node API - ApiCall Support
  description: Existing Node API endpoints support ApiCall node type
  version: 1.0.0

paths:
  /api/flows/{flowId}/nodes:
    post:
      summary: Create a new node in a flow
      description: |
        Creates a node of the specified type. For ApiCall nodes, the type
        should be 'ApiCall' and parameters should follow ApiCallNodeParameters.
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNodeRequest'
            examples:
              apiCall:
                summary: Create API Call node
                value:
                  type: ApiCall
                  name: Fetch User Data
                  position:
                    x: 300
                    y: 200
                  parameters:
                    method: GET
                    url: https://api.example.com/users
                    headers: []
                    timeout: 30000
      responses:
        '201':
          description: Node created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'

  /api/flows/{flowId}/nodes/{nodeId}:
    patch:
      summary: Update an existing node
      description: Updates node properties including parameters for ApiCall nodes.
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNodeRequest'
            examples:
              updateApiCall:
                summary: Update API Call configuration
                value:
                  name: Fetch User Profile
                  parameters:
                    method: POST
                    url: https://api.example.com/users/{{userId}}
                    headers:
                      - key: Content-Type
                        value: application/json
      responses:
        '200':
          description: Node updated successfully

components:
  schemas:
    NodeType:
      type: string
      enum:
        - Interface
        - Return
        - CallFlow
        - ApiCall
      description: Supported node types

    Position:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: number
        y:
          type: number

    HttpMethod:
      type: string
      enum:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH

    HeaderEntry:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
          description: Header name
        value:
          type: string
          description: Header value

    InputMapping:
      type: object
      required:
        - sourceNodeId
        - sourcePath
        - targetField
      properties:
        sourceNodeId:
          type: string
          format: uuid
        sourcePath:
          type: string
          description: Path to extract from source output (e.g., 'data.id')
        targetField:
          type: string
          enum:
            - url
            - header
            - body
        targetKey:
          type: string
          description: For headers/body - which key to set

    ApiCallNodeParameters:
      type: object
      required:
        - method
        - url
      properties:
        method:
          $ref: '#/components/schemas/HttpMethod'
        url:
          type: string
          description: Target URL (may contain template variables)
        headers:
          type: array
          items:
            $ref: '#/components/schemas/HeaderEntry'
          default: []
        timeout:
          type: integer
          minimum: 1000
          maximum: 300000
          default: 30000
          description: Request timeout in milliseconds
        inputMappings:
          type: array
          items:
            $ref: '#/components/schemas/InputMapping'
          default: []

    NodeInstance:
      type: object
      required:
        - id
        - type
        - name
        - position
        - parameters
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/NodeType'
        name:
          type: string
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          type: object
          description: Type-specific parameters

    CreateNodeRequest:
      type: object
      required:
        - type
        - name
        - position
      properties:
        type:
          $ref: '#/components/schemas/NodeType'
        name:
          type: string
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          type: object

    UpdateNodeRequest:
      type: object
      properties:
        name:
          type: string
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          type: object

    ApiCallOutput:
      type: object
      required:
        - type
        - success
        - requestDuration
      properties:
        type:
          type: string
          const: apiCall
        success:
          type: boolean
          description: true if request completed (even 4xx/5xx)
        status:
          type: integer
          description: HTTP status code
        statusText:
          type: string
          description: HTTP status text
        headers:
          type: object
          additionalProperties:
            type: string
        body:
          description: Parsed response body (JSON or text)
        error:
          type: string
          description: Error message when success=false
        requestDuration:
          type: integer
          description: Time taken for request in milliseconds
