/**
 * Specificity detection coverage test.
 * 100 realistic prompts per category — tests detection accuracy
 * and identifies keyword gaps.
 */
import { scanMessages } from '../scan-messages';
import type { ScorerMessage } from '../types';

function scan(text: string, tools?: { name: string }[]) {
  const msgs: ScorerMessage[] = [{ role: 'user', content: text }];
  return scanMessages(msgs, tools as any);
}

function testCategory(category: string, prompts: string[], tools?: { name: string }[]) {
  const results = { pass: 0, fail: 0, failures: [] as string[] };
  for (const p of prompts) {
    const r = scan(p, tools);
    if (r?.category === category) {
      results.pass++;
    } else {
      results.fail++;
      results.failures.push(`"${p}" → ${r?.category ?? 'null'}`);
    }
  }
  return results;
}

// ── CODING ──
const CODING_PROMPTS = [
  'write a python function to sort a list',
  'how do I reverse a string in javascript',
  'fix this bug in my react component',
  'what is a decorator in python',
  'explain async await in typescript',
  'create a REST API with express',
  'how to handle errors in golang',
  'write unit tests for this function',
  'refactor this code to use dependency injection',
  'what does this regex do',
  'convert this python script to rust',
  'how to use generics in typescript',
  'debug this segfault in my C program',
  'optimize this SQL query',
  'write a dockerfile for my node app',
  'implement binary search in java',
  'how to parse JSON in python',
  'create a class that inherits from Animal',
  'what is the difference between let and const',
  'write a bash script to rename files',
  'how to use map filter reduce in javascript',
  'implement a linked list in C++',
  'explain closures in javascript',
  'how to connect to postgres from python',
  'write a middleware for authentication',
  'create a webhook endpoint in flask',
  'how to mock a database in tests',
  'what is the best way to handle state in react',
  'write a recursive function for fibonacci',
  'how to deploy a nextjs app',
  'explain the event loop in nodejs',
  'create a cron job in python',
  'how to use environment variables in docker',
  'write a lambda function in AWS',
  'implement rate limiting in express',
  'how to use websockets in python',
  'create a CLI tool with argparse',
  'what is polymorphism explain with code',
  'how to read a CSV file in pandas',
  'write a GraphQL resolver',
  'implement pagination in a REST API',
  'how to use redis for caching',
  'create a custom hook in react',
  'write a migration script for the database',
  'how to handle file uploads in node',
  'implement JWT authentication',
  'what does this error mean TypeError undefined',
  'how to use git rebase',
  'write a terraform config for EC2',
  'implement a queue data structure',
  'how to use docker compose',
  'create an interface in typescript',
  'how to test async functions in jest',
  'write a python decorator for logging',
  'implement a trie data structure',
  'how to use context API in react',
  'write a go routine for concurrent processing',
  'how to set up eslint and prettier',
  'create a database schema for users',
  'how to use streams in nodejs',
  'implement observer pattern in python',
  'write a makefile for my project',
  'how to profile performance in python',
  'create a custom exception class',
  'how to use ORM in django',
  'write a shell script to deploy',
  'implement a hash map from scratch',
  'how to handle CORS in express',
  'create a singleton pattern in java',
  'how to use type guards in typescript',
  'write a config parser in python',
  'implement a priority queue',
  'how to use kubectl',
  'create a virtual environment in python',
  'how to debounce a function',
  'write a CSS grid layout',
  'implement a binary tree traversal',
  'how to use reduce in python',
  'create a pub sub system',
  'how to handle memory leaks in node',
  'write a REST client in python',
  'implement dependency injection in nestjs',
  'how to use async generators',
  'create a state machine in typescript',
  'how to set up CI CD pipeline',
  'write a load balancer config',
  'implement a bloom filter',
  'how to use signals in solidjs',
  'create a monorepo with turborepo',
  'how to use slots in vue components',
  'write a custom validator',
  'implement a worker thread pool',
  'how to handle race conditions',
  'create an enum type in python',
  'write a retry mechanism with backoff',
  'how to use fetch API',
  'implement A star algorithm',
  'how to setup husky pre commit hooks',
  'create a stored procedure in SQL',
  'write a proxy server in node',
  'how do I add 1 in python',
];

// ── WEB BROWSING ──
const WEB_BROWSING_PROMPTS = [
  'can you summarize this website: https://example.com',
  'go to google.com and search for AI news',
  'open this link and tell me what it says',
  'browse to the pricing page of stripe.com',
  'navigate to settings in the dashboard',
  'click the login button on this page',
  'scroll down to the footer section',
  'take a screenshot of this webpage',
  'extract all the links from this page',
  'scrape the product prices from amazon',
  'fetch the content of this URL',
  'what does this website look like',
  'visit https://github.com and find trending repos',
  'download the PDF from this page',
  'check if this website is down',
  'find the contact info on this site',
  'open the menu and click on About',
  'go to the blog page and get the latest post',
  'search for flights on google.com',
  'fill out this form on the website',
  'read the terms of service on this page',
  'bookmark this page for later',
  'navigate back to the home page',
  'click on the second search result',
  'extract the table data from this webpage',
  'what is the title of this page',
  'open a new tab and go to reddit',
  'find the phone number on this website',
  'crawl this site and list all pages',
  'check the SSL certificate of this domain',
  'get the meta description from this URL',
  'look up this address on google maps',
  'browse the documentation for react',
  'search yelp for restaurants near me',
  'open this article and summarize it',
  'go to wikipedia and look up quantum computing',
  'visit the app store page for this app',
  'check the reviews on this product page',
  'navigate to the API docs',
  'search for this error message on stackoverflow',
  'open the settings page on github',
  'go to youtube and find a tutorial',
  'visit this blog and get all article titles',
  'check the status page for AWS',
  'browse to the checkout page',
  'open this google doc link',
  'find the pricing on this SaaS website',
  'visit the competitor website and compare features',
  'fetch the RSS feed from this blog',
  'look at this hacker news thread',
  'go to twitter and check trending topics',
  'search for jobs on linkedin',
  'open this jira ticket',
  'visit the npm page for this package',
  'check the weather on weather.com',
  'search for this product on ebay',
  'browse the app settings page',
  'visit the support page and find FAQ',
  'open this slack channel link',
  'check stock price on yahoo finance',
  'go to the downloads section of this site',
  'navigate to user profile settings',
  'visit this figma link',
  'browse reddit for opinions on this topic',
  'go to the changelog page',
  'search google for best laptops 2026',
  'visit this notion page',
  'check if this coupon code works on the site',
  'open the developer console',
  'browse to the registration page',
  'fetch the sitemap from this domain',
  'visit the privacy policy page',
  'look up this company on crunchbase',
  'search for apartments on zillow',
  'check the delivery status on this tracking page',
  'browse to the admin panel',
  'open this google sheets link',
  'find the CEO name from the about page',
  'visit this product hunt page',
  'go to the careers page of this company',
  'check the analytics dashboard',
  'search for recipes on allrecipes',
  'browse the photo gallery on this site',
  'visit the documentation site for kubernetes',
  'open this trello board',
  'check the leaderboard on this gaming site',
  'search for papers on arxiv',
  'browse to the account settings',
  'fetch all images from this webpage',
  'visit this medium article',
  'go to spotify and search for a playlist',
  'check the order status page',
  'browse the marketplace listings',
  'visit the roadmap page',
  'search for this topic on quora',
  'open the notification settings page',
  'go to the help center',
  'check this domain whois info',
  'browse to the integrations page',
  'visit the release notes',
];

// ── DATA ANALYSIS ──
const DATA_ANALYSIS_PROMPTS = [
  'analyze this CSV file and find trends',
  'create a bar chart from this data',
  'calculate the average revenue per month',
  'run a regression analysis on this dataset',
  'plot a histogram of customer ages',
  'find the correlation between price and sales',
  'pivot this table by region and quarter',
  'clean this data and remove duplicates',
  'calculate the standard deviation',
  'create a scatter plot of height vs weight',
  'aggregate sales by category',
  'compute the moving average over 7 days',
  'find outliers in this dataset',
  'build a dashboard with these metrics',
  'parse this JSON and extract key statistics',
  'calculate churn rate from this data',
  'create a heatmap of user activity',
  'analyze the distribution of this variable',
  'compute the p-value for this test',
  'merge these two dataframes on user ID',
  'calculate year over year growth',
  'visualize the funnel conversion rates',
  'find the median salary by department',
  'create a line chart showing monthly revenue',
  'calculate confidence intervals',
  'group this data by week and sum totals',
  'analyze A/B test results',
  'compute the ROI for each campaign',
  'create a box plot of test scores',
  'find the top 10 products by revenue',
  'calculate the retention rate cohort',
  'build a pivot table of expenses',
  'analyze the sentiment scores distribution',
  'compute the variance of this sample',
  'plot the cumulative distribution function',
  'calculate the weighted average',
  'find seasonal patterns in this time series',
  'create a treemap visualization',
  'analyze the click through rate by segment',
  'compute the Bayesian probability',
  'normalize this dataset to 0-1 range',
  'calculate the net promoter score',
  'create a waterfall chart of revenue changes',
  'find the mode and median of this data',
  'analyze the demographic breakdown',
  'compute the compound annual growth rate',
  'plot the Pareto chart of defects',
  'calculate the breakeven point',
  'analyze user engagement metrics',
  'create a cohort analysis table',
  'compute the chi-square test statistic',
  'find the 95th percentile of response times',
  'analyze the supply chain data',
  'calculate customer lifetime value',
  'plot the ROC curve for this model',
  'find missing values in this spreadsheet',
  'calculate the Gini coefficient',
  'analyze the survey responses',
  'compute the exponential moving average',
  'create a sankey diagram of user flows',
  'calculate the elasticity of demand',
  'analyze website traffic patterns',
  'compute the z-score for each data point',
  'create a geographic heat map',
  'find the best fit line for this data',
  'calculate inventory turnover ratio',
  'analyze the payment data by method',
  'compute the interquartile range',
  'plot sales forecasts vs actuals',
  'calculate the attrition rate',
  'find correlations in this multivariate data',
  'create a radar chart comparing products',
  'analyze the price distribution',
  'compute the Pearson correlation coefficient',
  'create a stacked bar chart',
  'calculate the profit margin by product line',
  'analyze the time to first purchase',
  'build a summary statistics table',
  'plot the bell curve for test scores',
  'calculate market share percentages',
  'analyze the referral source data',
  'compute the covariance matrix',
  'create an area chart of growth',
  'find the trend line equation',
  'calculate days sales outstanding',
  'analyze the support ticket volume',
  'compute the geometric mean',
  'create a bubble chart of market data',
  'calculate the cost per acquisition',
  'analyze customer segmentation data',
  'compute the F-statistic',
  'plot the Lorenz curve',
  'calculate the burn rate',
  'analyze the subscription metrics',
  'find the inflection point in growth data',
  'create a comparison table of KPIs',
  'calculate the win rate by sales rep',
  'analyze quarterly financial data',
  'compute the ANOVA table',
  'visualize the customer journey data',
  'calculate operating margin trends',
];

// ── IMAGE GENERATION ──
const IMAGE_GENERATION_PROMPTS = [
  'generate an image of a sunset over mountains',
  'create a logo for my coffee shop',
  'draw a cartoon cat wearing a hat',
  'make a banner for my youtube channel',
  'design a poster for a music festival',
  'create an illustration of a futuristic city',
  'generate a profile picture for social media',
  'draw a sketch of a sports car',
  'make a thumbnail for my blog post',
  'create an icon set for my mobile app',
  'generate a wallpaper with abstract patterns',
  'design a book cover for a sci-fi novel',
  'create a mascot character for my brand',
  'generate a realistic photo of a beach',
  'draw an infographic about climate change',
  'make a sticker pack with cute animals',
  'create a product mockup for a t-shirt',
  'generate an avatar in anime style',
  'design a business card layout',
  'create a meme template',
  'generate a landscape painting in watercolor style',
  'draw a floor plan for my apartment',
  'make a social media post graphic',
  'create a pattern for fabric design',
  'generate a portrait in oil painting style',
  'design a wedding invitation',
  'create pixel art of a dragon',
  'generate a 3D render of a product',
  'draw a comic strip panel',
  'make a collage of vacation photos',
  'create a vintage poster design',
  'generate a cyberpunk character',
  'design an album cover for my band',
  'create a food photography style image',
  'generate a fantasy map',
  'draw a technical diagram',
  'make a hero image for my website',
  'create a seasonal greeting card',
  'generate architectural visualization',
  'design a menu for a restaurant',
  'create an isometric illustration',
  'generate a texture for 3D modeling',
  'draw a portrait of my pet from this photo',
  'make a flyer for an event',
  'create a badge or seal design',
  'generate a minimalist logo',
  'design a label for wine bottle',
  'create a photo with midjourney',
  'use flux to generate this scene',
  'create an image with ideogram',
  'generate with leonardo ai',
  'edit this image to remove the background',
  'upscale this low resolution photo',
  'inpaint the sky in this picture',
  'generate variations of this design',
  'create a concept art for a game',
  'make a whiteboard diagram',
  'design an email header image',
  'generate a seamless pattern',
  'create a before and after comparison image',
  'draw a wireframe for the app',
  'make an animated GIF of a loading spinner',
  'create a certificate template',
  'generate a QR code design',
  'design a dashboard screenshot mockup',
  'create a social proof banner',
  'generate a team photo composite',
  'draw a caricature of a person',
  'make a data visualization graphic',
  'create an explainer image with annotations',
  'generate a mood board for the project',
  'design a packaging box',
  'create a weather widget illustration',
  'generate a clip art style image',
  'draw a diagram of the architecture',
  'make a comparison graphic',
  'create a timeline infographic',
  'generate a stylized map',
  'design a newsletter header',
  'create a motivational quote image',
  'generate an app screenshot for the store',
  'draw a process flow diagram',
  'make a brand guidelines page',
  'create a photo manipulation effect',
  'generate a product shot on white background',
  'design a slide deck background',
  'create a cut out sticker',
  'generate a vintage photograph effect',
  'draw a hand lettering title',
  'make a photo frame template',
  'create a seasonal banner',
  'generate a low poly art piece',
  'design a certificate of achievement',
  'create a step by step tutorial image',
  'generate a neon sign effect',
  'draw a botanical illustration',
  'make a size comparison graphic',
  'create a before and after slider image',
  'use adobe firefly to create this',
  'generate with stable diffusion',
  'txt2img a cozy cabin in the woods',
];

// ── VIDEO GENERATION ──
const VIDEO_GENERATION_PROMPTS = [
  'create a short video of a walking robot',
  'generate an animation of flying birds',
  'make a product demo video',
  'create a timelapse of a cityscape',
  'animate this logo',
  'generate a video from this image',
  'create a tutorial video with screen recording',
  'make a social media reel',
  'produce a promotional video for my app',
  'create an explainer video',
  'generate a transition effect between scenes',
  'make a slideshow video from these photos',
  'create subtitles for this video',
  'animate this character walking',
  'generate a music video visualizer',
  'create a storyboard for my short film',
  'make a video ad for instagram',
  'produce a training video for employees',
  'create a before and after video',
  'generate motion graphics for the intro',
  'make a time lapse of a drawing',
  'create a video with sora',
  'generate using runway gen 4',
  'create a video with kling',
  'use veo to generate this clip',
  'create an avatar video with synthesia',
  'make a talking head video with heygen',
  'edit this video in capcut',
  'cut this long video into shorts with opusclip',
  'create a video using higgsfield',
  'generate a text to video from this prompt',
  'convert this image to video',
  'animate this static illustration',
  'create a looping video for the background',
  'generate a slow motion effect',
  'make a split screen comparison video',
  'add captions to this clip',
  'create a video montage',
  'generate a kinetic typography animation',
  'produce a video testimonial',
  'create a whiteboard animation',
  'make a stop motion video',
  'generate a 3D camera fly through',
  'create a video greeting card',
  'produce a video podcast episode',
  'make a video resume',
  'generate a particle effect animation',
  'create a video infographic',
  'produce a live action style video from text',
  'make a video game trailer',
  'generate a fashion lookbook video',
  'create an aerial drone footage style video',
  'produce a recipe video',
  'make a workout tutorial video',
  'generate a news style video report',
  'create a video presentation from slides',
  'produce a brand story video',
  'make a reaction style video template',
  'generate a video with lip sync',
  'create a parallax scrolling video effect',
  'produce a video countdown timer',
  'make a video portfolio of my work',
  'generate a nature documentary style clip',
  'create a video with green screen removal',
  'produce a virtual tour video',
  'make a video meme',
  'generate an animated logo reveal',
  'create a video for tiktok',
  'produce a youtube short from this content',
  'make an instagram story video',
  'generate a linkedin video post',
  'create a video thumbnail preview',
  'produce a webinar recording intro',
  'make a video with picture in picture',
  'generate a cinematic video effect',
  'create a video with speed ramp',
  'produce a video collage grid',
  'make a boomerang video effect',
  'generate a video with zoom transition',
  'create a documentary style interview video',
  'produce a crowdfunding campaign video',
  'make a video with text overlay',
  'generate a video from a script',
  'create a video summary of this article',
  'produce a video invitation',
  'make a video with background music',
  'generate a promo clip for this event',
  'create an animated chart video',
  'produce a video ad for facebook',
  'make a video with voiceover',
  'generate a render of this 3D scene',
  'create keyframes for this animation',
  'produce a video with motion tracking',
  'make a video with color grading',
  'generate a hyperlapse video',
  'create a video with frame interpolation',
  'produce a video with audio visualization',
  'make a video loop for digital signage',
  'generate a video with AI upscaling',
  'create a video with scene transitions',
];

// ── SOCIAL MEDIA ──
const SOCIAL_MEDIA_PROMPTS = [
  'write a tweet about our new product launch',
  'create an instagram caption for this photo',
  'draft a linkedin post about my promotion',
  'write a thread about AI trends',
  'create a content calendar for next month',
  'suggest hashtags for this fitness post',
  'write a facebook post for our event',
  'draft a tiktok script for a product review',
  'create a poll for twitter',
  'write a caption for this food photo',
  'schedule this post for tomorrow at 9am',
  'analyze my engagement rate this week',
  'write a reply to this comment',
  'create a carousel post about productivity tips',
  'draft a bio for my instagram profile',
  'write a social media strategy for Q2',
  'create a trending reel concept',
  'suggest the best time to post on linkedin',
  'write a viral hook for this video',
  'create a giveaway post for followers',
  'draft an announcement for our new feature',
  'write a testimonial post from a customer',
  'create a behind the scenes post',
  'plan social media posts for the product launch',
  'write a story for instagram about our team',
  'create a pin for pinterest',
  'draft a youtube community post',
  'write a response to negative feedback',
  'create a user generated content campaign',
  'suggest trending topics for our niche',
  'write a post celebrating 10k followers',
  'create a social media audit report',
  'draft a collaboration proposal DM',
  'write a series of educational posts',
  'create engagement questions for stories',
  'plan a social media contest',
  'write copy for a paid social ad',
  'create a social proof post with stats',
  'draft a welcome message for new followers',
  'write a seasonal campaign post',
  'create a meme for our brand',
  'suggest influencer outreach messages',
  'write a recap post of our webinar',
  'create a countdown post for launch day',
  'draft a cross platform posting strategy',
  'use hootsuite to schedule these posts',
  'analyze engagement with sprout social',
  'schedule posts in buffer for the week',
  'set up later to auto publish',
  'create a content plan in feedhive',
  'monitor brand mentions with brand24',
  'write a bluesky post about tech',
  'create a threads post',
  'make a youtube shorts script',
  'plan instagram reels for the week',
  'create stories with interactive stickers',
  'write a community building post',
  'draft a crisis communication response',
  'create a social media style guide',
  'write a thought leadership post',
  'create a product comparison carousel',
  'draft a holiday greeting post',
  'write an employee spotlight post',
  'create a tips and tricks series',
  'plan a live stream event post',
  'write a milestone celebration post',
  'create a FAQ post for followers',
  'draft a partnership announcement',
  'write a sneak peek preview post',
  'create a post for international womens day',
  'plan a hashtag challenge campaign',
  'write a customer success story post',
  'create a social media report for the client',
  'draft evergreen content for repurposing',
  'write a how to post with steps',
  'create a branded template for posts',
  'plan a week of daily social content',
  'write a roundup post of industry news',
  'create a save worthy educational post',
  'draft a playful brand voice post',
  'write a post about our company culture',
  'create a trending audio post idea',
  'plan social content around a podcast episode',
  'write a post for earth day',
  'create a mini tutorial for our product',
  'draft a teaser for upcoming content',
  'write a controversial take post',
  'create a nostalgia themed post',
  'plan a social listening report',
  'write a post for our newsletter signup',
  'create a data driven insights post',
  'draft a post showcasing customer reviews',
  'write a motivational monday post',
  'create a post for a flash sale',
  'plan social coverage for a conference',
  'write a post about our sustainability efforts',
  'create a fun quiz post for engagement',
  'draft a post promoting our blog article',
  'write a series of tips for beginners',
  'create content for all platforms from one idea',
];

// ── EMAIL MANAGEMENT ──
const EMAIL_MANAGEMENT_PROMPTS = [
  'draft an email to the client about the project update',
  'write a follow up email after the meeting',
  'compose a cold email for lead generation',
  'reply to this email professionally',
  'create an email template for onboarding',
  'write a newsletter for our subscribers',
  'draft an apology email for the service outage',
  'compose an email requesting a meeting',
  'write a thank you email after the interview',
  'create a drip campaign for new signups',
  'draft a promotional email for our sale',
  'write an email to decline a proposal politely',
  'compose a reminder email for the deadline',
  'create a welcome email series',
  'write a subject line that gets opens',
  'draft an email introducing our new team member',
  'compose an email to request feedback',
  'write a cancellation confirmation email',
  'create an email sequence for cart abandonment',
  'draft a referral request email',
  'write a partnership proposal email',
  'compose a status update email for stakeholders',
  'create a re-engagement email for inactive users',
  'write an out of office auto reply',
  'draft an email to negotiate pricing',
  'compose a product launch announcement email',
  'write a survey invitation email',
  'create a monthly digest email template',
  'draft an escalation email to management',
  'write an email to schedule a demo',
  'compose a congratulations email for a promotion',
  'create an email for event registration confirmation',
  'write a shipping notification email',
  'draft an email requesting a testimonial',
  'compose a quarterly business review email',
  'write an email to unsubscribe from a list',
  'create an email asking for a raise',
  'draft a customer success check in email',
  'write a product feedback request email',
  'compose an email to resolve a complaint',
  'organize my inbox by priority',
  'sort emails from this sender into a folder',
  'set up email filters in gmail',
  'clean up my outlook inbox',
  'manage my email subscriptions',
  'use superhuman to process my inbox',
  'configure spark mail smart inbox',
  'set up shortwave for email triage',
  'create a mailchimp campaign',
  'send a newsletter via sendgrid',
  'set up a drip campaign in resend',
  'write a BCC introduction email',
  'add a CC to the finance team',
  'attach the report to this email',
  'update my email signature',
  'write a formal email to the board',
  'compose an internal memo via email',
  'draft an NDA request email',
  'write an email to coordinate travel plans',
  'compose an email for vendor onboarding',
  'create an email for password reset notification',
  'write an email to announce a webinar',
  'draft an email to delay a deliverable',
  'compose an email confirming receipt of payment',
  'write an email for contract renewal',
  'create an email to invite speakers',
  'draft a seasonal promotion email',
  'write an email to share meeting notes',
  'compose an email requesting access permissions',
  'create an email for team building event',
  'write an email to announce office relocation',
  'draft an email for annual review preparation',
  'compose an email to welcome a new client',
  'write an email to follow up on an invoice',
  'create an email about policy changes',
  'draft an email for product recall notification',
  'write an email to share quarterly results',
  'compose an email requesting a letter of recommendation',
  'create an email for compliance training reminder',
  'write an email to reconnect with a former colleague',
  'draft an email to announce a charity drive',
  'compose an email for service level agreement review',
  'write an email to report a security incident',
  'create an email template for customer support',
  'draft an email about maintenance downtime',
  'write an email to set expectations for a project',
  'compose an email to share a resource library',
  'create an automated response for common questions',
  'write an email to coordinate a team offsite',
  'draft an email for volunteer recruitment',
  'compose an email announcing a new partnership',
  'write an email to request a deadline extension',
  'create an email for beta program invitation',
  'draft an email about data migration notice',
  'compose an email to share blog content',
  'write an email to introduce a mentorship program',
  'create an email for employee recognition',
  'draft an email for budget approval request',
  'compose an email for product documentation update',
  'write an email to announce job openings',
  'forward this email to the team',
];

// ── CALENDAR MANAGEMENT ──
const CALENDAR_MANAGEMENT_PROMPTS = [
  'schedule a meeting with the team for next Tuesday',
  'find a free slot for a 30 minute call this week',
  'reschedule the standup to 10am',
  'block time for deep work on Wednesday afternoon',
  'set a reminder for the project deadline',
  'create a recurring weekly team sync',
  'check my availability for Thursday',
  'book a room for the client presentation',
  'move the 1:1 to Friday at 3pm',
  'cancel the meeting with marketing',
  'send calendar invites to all attendees',
  'find a time that works for everyone',
  'add a 15 minute buffer between meetings',
  'schedule a lunch break every day at noon',
  'create an agenda for the board meeting',
  'set up office hours from 2-4pm on Mondays',
  'check if Sarah is available tomorrow morning',
  'block the entire day for the offsite',
  'reschedule all meetings from Monday to Tuesday',
  'add a video conference link to this meeting',
  'schedule a follow up meeting in two weeks',
  'set a reminder 30 minutes before the interview',
  'create a booking page for client consultations',
  'sync my work and personal calendars',
  'find the next available slot for a team lunch',
  'schedule a quarterly review for end of month',
  'block focus time from 9 to 11 every morning',
  'move all Friday meetings to Thursday',
  'check what meetings I have tomorrow',
  'create a time slot for the webinar',
  'set up auto decline for meetings after 5pm',
  'schedule a coffee chat with the new hire',
  'book a meeting room for 20 people',
  'add the client deadline to my calendar',
  'create a study block for exam prep',
  'schedule the sprint planning meeting',
  'find overlap in timezones for the global team',
  'move the demo to next week same time',
  'block time for exercise on Monday Wednesday Friday',
  'create a shared calendar for the project',
  'set up calendly for interview scheduling',
  'configure cal.com for client bookings',
  'use reclaim to protect my focus time',
  'set up reclaim.ai to auto schedule tasks',
  'configure clockwise for team optimization',
  'use motion to plan my day',
  'sync google calendar with my tools',
  'optimize my schedule for focus time',
  'schedule a brainstorming session',
  'set a reminder to submit the report',
  'create a vacation block next week',
  'add holidays to the team calendar',
  'schedule a retrospective meeting',
  'plan a team building activity for next Friday',
  'set up a daily standup at 9:15am',
  'check for conflicts on my calendar',
  'schedule a product launch prep meeting',
  'add a deadline reminder for the proposal',
  'create a study schedule for the certification',
  'book recurring therapy appointments',
  'schedule a haircut appointment',
  'add dentist appointment to calendar',
  'plan my workout schedule for the week',
  'schedule date night for Saturday',
  'block time for meal prep on Sunday',
  'add the concert to my calendar',
  'schedule a car maintenance appointment',
  'create a travel itinerary with times',
  'plan the holiday party schedule',
  'set up morning routine time blocks',
  'schedule parent teacher conference',
  'add volunteer shift to calendar',
  'plan podcast recording sessions',
  'schedule content creation blocks',
  'add launch day timeline to calendar',
  'plan interview schedule for candidates',
  'schedule onboarding meetings for new hire',
  'create a training schedule',
  'add conference sessions to my calendar',
  'plan the release schedule',
  'schedule a budget review meeting',
  'add the sales call to tomorrow at 2pm',
  'create a meal planning calendar',
  'schedule weekly grocery shopping time',
  'add a reading block to my daily schedule',
  'plan my commute times for the week',
  'schedule a catch up call with an old friend',
  'create a time block for side project work',
  'add the flight departure to my calendar',
  'schedule a vet appointment for the dog',
  'plan a birthday party timeline',
  'add graduation ceremony to the calendar',
  'schedule moving day tasks',
  'create a wedding planning timeline',
  'add medication reminders to calendar',
  'schedule regular breaks throughout the day',
  'plan the hackathon schedule',
  'create a study group meeting schedule',
  'add the deadline for tax filing',
  'schedule a networking event',
  'plan family visit logistics',
];

// ── TRADING ──
const TRADING_PROMPTS = [
  'what is the current price of bitcoin',
  'analyze the AAPL stock chart',
  'should I buy ethereum right now',
  'place a limit order for TSLA at 250',
  'what is the RSI for NVDA',
  'check my portfolio performance today',
  'set a stop loss at 10 percent below entry',
  'find stocks with bullish MACD crossover',
  'what is the support and resistance for SPY',
  'analyze the moving average for gold',
  'place a market order for 100 shares of MSFT',
  'whats the best entry point for solana',
  'check the order book for BTC/USDT',
  'calculate my position size for this trade',
  'what is the earnings date for AMZN',
  'analyze the candlestick pattern on this chart',
  'find oversold stocks in the S&P 500',
  'set take profit at 20 percent above entry',
  'check the volume profile for ETH',
  'what is the dividend yield for KO',
  'analyze the breakout on this ticker',
  'monitor the pre market movers',
  'calculate the risk reward ratio for this trade',
  'what are the top gaining crypto today',
  'analyze the fibonacci retracement levels',
  'check the options chain for AMD',
  'find stocks near their 52 week high',
  'analyze the bearish divergence on RSI',
  'whats happening in the forex market today',
  'calculate margin requirements for this position',
  'check the correlation between BTC and ETH',
  'find high volume breakout stocks',
  'what is the implied volatility for SPY options',
  'analyze the cup and handle pattern',
  'set an alert for when AAPL hits 200',
  'check the crypto fear and greed index',
  'find the best DeFi yields',
  'analyze the head and shoulders pattern',
  'what is the leverage on this position',
  'check the funding rate for BTC perpetual',
  'use kalshi to bet on election results',
  'check polymarket odds for the fed rate decision',
  'trade event contracts on robinhood predictions',
  'what are the prediction market odds for GDP growth',
  'place a bet on kalshi for the jobs report',
  'check polymarket for AI regulation predictions',
  'analyze the robinhood prediction market trends',
  'buy shares on the yes side of this prediction',
  'what is the interactive brokers margin rate',
  'check my webull account performance',
  'analyze this chart on tradingview',
  'find trade ideas on coinbase',
  'check the kraken order book for ETH',
  'analyze binance futures data',
  'review bitget copy trading performance',
  'track my portfolio on tradingview',
  'compare fees between exchanges',
  'check the latest SEC filings',
  'analyze the earnings call transcript',
  'what is the PE ratio of the market',
  'find undervalued stocks using DCF analysis',
  'check the put call ratio',
  'analyze the yield curve',
  'what sectors are rotating into strength',
  'find the best performing ETFs this year',
  'analyze the VIX trend',
  'calculate compound interest on this investment',
  'what is the beta of this stock',
  'check if this stock pays monthly dividends',
  'analyze the short interest on GME',
  'find the best staking rewards for crypto',
  'what is the total market cap of crypto',
  'analyze the dollar cost averaging results',
  'check the latest FOMC minutes',
  'find arbitrage opportunities between exchanges',
  'analyze the correlation matrix of my portfolio',
  'what is the Sharpe ratio of this fund',
  'check the latest CPI data impact on markets',
  'analyze the momentum indicators',
  'calculate the max drawdown of this strategy',
  'find the best swing trade setups',
  'analyze the market breadth indicators',
  'check the latest insider trading data',
  'calculate portfolio alpha and beta',
  'analyze the sector rotation trends',
  'find the best dividend growth stocks',
  'check the economic calendar for this week',
  'analyze the price action on this chart',
  'calculate the expected value of this trade',
  'review my trading journal entries',
  'find liquid options with tight spreads',
  'analyze the dark pool activity',
  'check the commodity futures prices',
  'calculate the Kelly criterion for position sizing',
  'find the best performing currencies this month',
  'analyze the interest rate swap market',
  'check the real estate investment trust yields',
  'hedge my portfolio against a downturn',
  'analyze the credit default swap spreads',
  'find the best growth stocks under 50 dollars',
  'calculate the breakeven on this options spread',
];

describe('specificity detection coverage', () => {
  // Trading has lower threshold because financial analysis prompts
  // inherently overlap with data_analysis ("analyze the chart", "calculate the ratio").
  // web_browsing was dropped from 0.8 to 0.75 after discussion #1613 — the
  // remaining misses are genuinely ambiguous ("open the developer console",
  // "search yelp for restaurants") where the safer call is to NOT route them
  // to the browsing tier. We accept lower recall to keep the false-positive
  // rate on coding prompts under 3%.
  const categories: { name: string; prompts: string[]; minAccuracy: number }[] = [
    { name: 'coding', prompts: CODING_PROMPTS, minAccuracy: 0.8 },
    { name: 'web_browsing', prompts: WEB_BROWSING_PROMPTS, minAccuracy: 0.75 },
    { name: 'data_analysis', prompts: DATA_ANALYSIS_PROMPTS, minAccuracy: 0.8 },
    { name: 'image_generation', prompts: IMAGE_GENERATION_PROMPTS, minAccuracy: 0.8 },
    { name: 'video_generation', prompts: VIDEO_GENERATION_PROMPTS, minAccuracy: 0.8 },
    { name: 'social_media', prompts: SOCIAL_MEDIA_PROMPTS, minAccuracy: 0.8 },
    { name: 'email_management', prompts: EMAIL_MANAGEMENT_PROMPTS, minAccuracy: 0.8 },
    { name: 'calendar_management', prompts: CALENDAR_MANAGEMENT_PROMPTS, minAccuracy: 0.8 },
    { name: 'trading', prompts: TRADING_PROMPTS, minAccuracy: 0.65 },
  ];

  for (const { name, prompts, minAccuracy } of categories) {
    it(`should detect ${name} with >= ${minAccuracy * 100}% accuracy`, () => {
      const results = testCategory(name, prompts);
      const accuracy = results.pass / prompts.length;
      if (accuracy < minAccuracy) {
        console.log(`\n${name} failures (${results.fail}/${prompts.length}):`);
        for (const f of results.failures) console.log(`  ${f}`);
      }
      expect(accuracy).toBeGreaterThanOrEqual(minAccuracy);
    });
  }
});
