// Builds the registry artifacts from the resolved cascade:
// registry/components.json (machine) and registry/llms.txt (agent-readable).

const CATEGORY_RULES = [
  ['chart', /^--(chart|bar)-/],
  ['sidebar', /^--sidebar-/],
  ['font', /^--(font|tooltip-font)/],
  ['gap', /^--gap-/],
  ['z-index', /^--z-/],
  ['shadow', /^--(shadow|card-shadow)/],
  ['radius', /^--radius/],
  ['transition', /^--transition-/],
  ['layout', /^--(sidebar-width|header-height)$/],
];

export function categorize(prop) {
  for (const [cat, re] of CATEGORY_RULES) if (re.test(prop)) return cat;
  return 'color';
}

/** tokens: { light: Map, dark: Map } → { category: { name: { light, dark? } } } */
export function tokenCatalog({ light, dark }) {
  const catalog = {};
  for (const [prop, def] of light) {
    const cat = (catalog[categorize(prop)] ??= {});
    const darkDef = dark.get(prop);
    cat[prop] = { light: def.value, ...(darkDef ? { dark: darkDef.value } : {}) };
  }
  for (const [prop, def] of dark) {
    if (light.has(prop)) continue;
    const cat = (catalog[categorize(prop)] ??= {});
    cat[prop] = { dark: def.value };
  }
  return sortObject(catalog, (o) => sortObject(o));
}

const sortObject = (obj, mapValue = (v) => v) =>
  Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => [k, mapValue(v)]));

export function buildRegistry(input) {
  const { tokens, blocks, canonical, ghosts, orphans, componentSheets, outOfSource, primitives, migrationMap } = input;
  const blockEntries = Object.fromEntries(blocks);
  return {
    $comment: 'GENERATED by design-system/generate-registry.mjs — do not edit. Regenerate with: npm run design:registry',
    source: 'packages/frontend/src/styles (entry: theme.css + component-imported sheets)',
    tokens: tokenCatalog(tokens),
    blocks: blockEntries,
    primitives,
    migrationMap,
    canonicalRules: canonical,
    ghostRules: ghosts,
    componentSheets,
    orphanStylesheets: orphans,
    tokensOutsideSource: outOfSource,
    stats: {
      tokens: tokens.light.size,
      darkOverrides: tokens.dark.size,
      blocks: blocks.size,
      classes: Object.values(blockEntries).reduce((n, b) => n + b.classes.length, 0),
      canonicalRules: canonical.length,
      ghostRules: ghosts.length,
    },
  };
}

export function buildLlmsTxt(registry) {
  const lines = [
    '# Manifest platform design-system registry (GENERATED — do not edit)',
    '# Regenerate: npm run design:registry — source: packages/frontend/src/styles, entry theme.css',
    '#',
    '# Rules for any UI change: use these tokens (never raw hex/hsl/px sizes),',
    '# reuse an existing block before inventing one, and when a canonical rule',
    '# exists for a selector, edit THAT rule — never add a competing one.',
    '',
    `## Tokens (${registry.stats.tokens} on :root, ${registry.stats.darkOverrides} dark overrides)`,
  ];
  for (const [category, tokens] of Object.entries(registry.tokens)) {
    lines.push(`### ${category}`);
    for (const [name, v] of Object.entries(tokens)) {
      lines.push(`${name}: ${v.light ?? '(dark only)'}${v.dark && v.dark !== v.light ? ` | dark: ${v.dark}` : ''}`);
    }
  }
  lines.push('', `## Blocks (${registry.stats.blocks} BEM blocks, ${registry.stats.classes} classes)`);
  for (const [block, entry] of Object.entries(registry.blocks)) {
    lines.push(`${block} (${entry.files.join(', ')}): ${entry.classes.join(' ')}`);
  }
  lines.push('', `## Primitives (${registry.primitives.length})`);
  lines.push(...(registry.primitives.length ? registry.primitives.map((p) => `${p.name}: ${p.file}`) : ['(none yet — phase 2 builds them in src/components/ui/)']));
  const mapped = Object.entries(registry.migrationMap);
  lines.push('', `## Migration map — legacy component → primitive to use instead (${mapped.length})`);
  lines.push(...(mapped.length ? mapped.map(([from, to]) => `${from} → ${to}`) : ['(empty until primitives exist)']));
  lines.push('', `## Canonical rules — same selector+property declared twice with different values; the winner renders (${registry.canonicalRules.length})`);
  for (const c of registry.canonicalRules) {
    lines.push(`${c.selector} { ${c.prop}: ${c.value} }  ← ${c.file}:${c.line}${c.media ? `  [@media ${c.media}]` : ''}`);
  }
  lines.push('', `## Ghost rules — declared but always losing; edit the canonical rule instead, delete these in the refactor project (${registry.ghostRules.length})`);
  for (const g of registry.ghostRules) {
    lines.push(`${g.selector} { ${g.prop}: ${g.value} }  at ${g.file}:${g.line} loses to ${g.losesTo}`);
  }
  const sheets = Object.entries(registry.componentSheets);
  if (sheets.length) {
    lines.push('', `## Component-loaded sheets — imported by components, not theme.css; they load after the global styles (${sheets.length})`);
    lines.push(...sheets.map(([f, by]) => `${f} ← ${by.join(', ')}`));
  }
  if (registry.orphanStylesheets.length) {
    lines.push('', `## Orphan stylesheets — in src/styles but imported nowhere (${registry.orphanStylesheets.length})`);
    lines.push(...registry.orphanStylesheets);
  }
  if (registry.tokensOutsideSource.length) {
    lines.push('', '## Token definitions outside tokens.css (single-source violations)');
    lines.push(...registry.tokensOutsideSource.map((t) => `${t.scope} ${t.prop} at ${t.file}:${t.line}`));
  }
  return lines.join('\n') + '\n';
}
