openapi: 3.0.3
info:
  title: UI Node Actions API
  description: API endpoint for handling UI node action callbacks
  version: 1.0.0

paths:
  /api/apps/{appSlug}/actions:
    post:
      summary: Execute a UI node action callback
      description: |
        Called when a user interacts with a UI component action (e.g., clicks "Read More" on a post).
        Executes the downstream nodes connected to the action handle and returns the result.
      operationId: executeAction
      tags:
        - Actions
      parameters:
        - name: appSlug
          in: path
          required: true
          description: The app's URL slug
          schema:
            type: string
            example: my-blog-app
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecuteActionRequest'
            example:
              toolName: get_posts
              nodeId: "abc123-def456"
              action: onReadMore
              data:
                id: "post-1"
                title: "Getting Started with TypeScript"
                excerpt: "Learn the basics of TypeScript..."
                author:
                  name: "Jane Developer"
                publishedAt: "2026-01-08"
      responses:
        '200':
          description: Action executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/McpToolResponse'
        '400':
          description: Invalid request (missing fields, invalid action)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: App, flow, node, or action not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ExecuteActionRequest:
      type: object
      required:
        - toolName
        - nodeId
        - action
        - data
      properties:
        toolName:
          type: string
          description: The trigger's tool name that initiated the flow
          example: get_posts
        nodeId:
          type: string
          description: The ID of the UI node that emitted the action
          example: abc123-def456
        action:
          type: string
          description: The action name (must match a defined action on the node)
          example: onReadMore
        data:
          type: object
          description: The data passed by the action (e.g., the Post object)
          additionalProperties: true

    McpToolResponse:
      type: object
      properties:
        content:
          type: array
          description: Text content for LLM processing
          items:
            type: object
            properties:
              type:
                type: string
                enum: [text]
              text:
                type: string
        structuredContent:
          type: object
          description: Structured data for programmatic consumption
          additionalProperties: true
        widget:
          type: object
          description: Widget metadata for UI rendering
          properties:
            type:
              type: string
            url:
              type: string
            title:
              type: string

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string
