# API Contract: Blank Component
# Feature: 001-blank-component
# Date: 2026-01-14
#
# Note: BlankComponent uses existing API endpoints.
# No new endpoints are required. This document describes
# how existing endpoints are used for BlankComponent.

openapi: 3.0.3
info:
  title: Blank Component API
  description: |
    The Blank Component feature uses existing node management APIs.
    This contract documents the relevant endpoints and their usage
    with BlankComponent nodes.
  version: 1.0.0

paths:
  /api/node-types:
    get:
      summary: Get available node types and categories
      description: |
        Returns all available node types including BlankComponent,
        and all categories including the new 'blank' category.
        Categories are ordered by the `order` field.
      operationId: getNodeTypes
      responses:
        '200':
          description: List of node types and categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodeTypes:
                    type: array
                    items:
                      $ref: '#/components/schemas/NodeTypeInfo'
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategoryInfo'
              example:
                nodeTypes:
                  - name: BlankComponent
                    displayName: Blank Component
                    description: Create your own custom UI component
                    category: blank
                    icon: square
                    inputs: [main]
                    outputs: [main]
                categories:
                  - id: blank
                    displayName: Blank
                    order: 0
                  - id: trigger
                    displayName: Triggers
                    order: 1

  /api/flows/{flowId}/nodes:
    post:
      summary: Add a node to a flow
      description: |
        Creates a new BlankComponent node with default template code.
        The node is added to the flow's nodes array.
      operationId: addNode
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddNodeRequest'
            example:
              type: BlankComponent
              name: My Custom Component
              position:
                x: 100
                y: 200
              parameters: {}
      responses:
        '201':
          description: Node created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'

  /api/flows/{flowId}/nodes/{nodeId}:
    patch:
      summary: Update a node
      description: |
        Updates a BlankComponent node, typically to save customized code
        or appearance configuration from the InterfaceEditor.
      operationId: updateNode
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNodeRequest'
            example:
              name: Updated Component Name
              parameters:
                customCode: |
                  export default function MyComponent({ data }) {
                    return <div>{data?.message}</div>;
                  }
                appearanceConfig:
                  variant: outlined
      responses:
        '200':
          description: Node updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'

components:
  schemas:
    NodeTypeInfo:
      type: object
      required:
        - name
        - displayName
        - category
        - inputs
        - outputs
      properties:
        name:
          type: string
          description: Internal node type identifier
          example: BlankComponent
        displayName:
          type: string
          description: Human-readable name shown in UI
          example: Blank Component
        description:
          type: string
          description: Brief description of what the node does
        category:
          $ref: '#/components/schemas/NodeTypeCategory'
        icon:
          type: string
          description: Lucide icon name
          example: square
        inputs:
          type: array
          items:
            type: string
          description: Input handle identifiers
        outputs:
          type: array
          items:
            type: string
          description: Output handle identifiers

    CategoryInfo:
      type: object
      required:
        - id
        - displayName
        - order
      properties:
        id:
          $ref: '#/components/schemas/NodeTypeCategory'
        displayName:
          type: string
          description: Human-readable category name
          example: Blank
        order:
          type: integer
          description: Sort order (lower numbers appear first)
          example: 0

    NodeTypeCategory:
      type: string
      enum:
        - blank
        - trigger
        - interface
        - action
        - return
        - transform
      description: Node type category identifier

    NodeInstance:
      type: object
      required:
        - id
        - slug
        - type
        - name
        - position
        - parameters
      properties:
        id:
          type: string
          format: uuid
        slug:
          type: string
          description: Auto-generated human-readable identifier
        type:
          type: string
          enum: [BlankComponent]
        name:
          type: string
          description: User-provided display name
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          $ref: '#/components/schemas/BlankComponentParameters'

    Position:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: number
        y:
          type: number

    BlankComponentParameters:
      type: object
      properties:
        customCode:
          type: string
          description: |
            User-customized TSX source code.
            If not provided, default template is used.
        appearanceConfig:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: number
              - type: boolean
          description: |
            Visual configuration options parsed from
            the component's TypeScript interface.

    AddNodeRequest:
      type: object
      required:
        - type
        - name
        - position
      properties:
        type:
          type: string
          enum: [BlankComponent]
        name:
          type: string
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          $ref: '#/components/schemas/BlankComponentParameters'

    UpdateNodeRequest:
      type: object
      properties:
        name:
          type: string
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          $ref: '#/components/schemas/BlankComponentParameters'
