name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Install the plugin via `openclaw plugins install manifest`
        2. Configure with `openclaw config set ...`
        3. ...
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - manifest (OpenClaw plugin)
        - "@mnfst/server (embedded server)"
        - Backend (self-hosted)
        - Frontend (dashboard)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "Package version (run `npm list manifest` or check package.json)"
      placeholder: "5.2.1"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: "Output of `node --version`"
      placeholder: "v22.x.x"

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste any error messages, logs, or screenshots.
      render: shell
