name: 🎨 Component Request
description: Request a new UI component for the registry
title: "[Component]: "
labels: ["enhancement", "component-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a new component! This helps us understand what the community needs.

  - type: input
    id: component-name
    attributes:
      label: Component Name
      description: What should this component be called?
      placeholder: e.g., "File Upload", "Progress Tracker", "Chat Input"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Component Category
      description: Which category does this component belong to?
      options:
        - blogging
        - events
        - form
        - list
        - messaging
        - payment
        - miscellaneous
        - new category (specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what this component does and why it's useful for MCP/ChatGPT apps.
      placeholder: |
        This component allows users to upload files in a chat interface. It would be useful for customer support bots that need to receive documents...
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Key Features
      description: List the main features this component should have.
      placeholder: |
        - Drag and drop support
        - Multiple file upload
        - File type validation
        - Progress indicator
    validations:
      required: true

  - type: textarea
    id: props
    attributes:
      label: Proposed Props/API
      description: What props or API should this component expose? (Optional but helpful)
      placeholder: |
        ```typescript
        interface FileUploadProps {
          data?: {
            maxFiles?: number
            acceptedTypes?: string[]
          }
          actions?: {
            onUpload?: (files: File[]) => void
          }
        }
        ```

  - type: textarea
    id: examples
    attributes:
      label: Examples or Inspiration
      description: Links to similar components, designs, or examples that illustrate your vision.
      placeholder: |
        - Dropzone from react-dropzone
        - Similar to Slack's file upload
        - Design reference: [link]

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this component would be used.
      placeholder: |
        1. Customer support bot receiving documents
        2. Resume upload for job application assistant
        3. Invoice submission for accounting bot

  - type: checkboxes
    id: willing-to-build
    attributes:
      label: Would you like to build this component?
      options:
        - label: Yes, I'd like to implement this component
        - label: Yes, I can help with design/testing
        - label: No, but I'd use it if someone builds it

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mnfst/manifest/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
