name: 💡 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please check [GitHub Discussions](https://github.com/mnfst/manifest/discussions) to see if someone else has already suggested this.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Which area does this feature affect?
      multiple: true
      options:
        - New UI component
        - Existing component enhancement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be valuable.
      placeholder: |
        When building a customer support chatbot, I need to...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or links to examples that illustrate your feature request.

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Would you be willing to contribute this feature?
      options:
        - label: Yes, I'd like to implement this feature
        - label: Yes, I can help with testing/feedback
        - label: No, but I'd like to see it implemented

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mnfst/manifest/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
