#!/usr/bin/env bash
# disaster-recovery.sh — Kill the WIP stack, spin up the DR stack over Tailscale.
#
# Usage:
#   ./disaster-recovery.sh              # stop WIP → start DR
#   ./disaster-recovery.sh status       # show both stacks
#   ./disaster-recovery.sh stop         # stop DR only
#   ./disaster-recovery.sh restore      # stop DR → start WIP
#
# First run: auto-generates BETTER_AUTH_SECRET, then starts everything.
# Requires Tailscale running on the host.

set -euo pipefail
cd "$(dirname "$0")"

COMPOSE_WIP="docker-compose.yml"
COMPOSE_DR="docker-compose.dr.yml"
ENV_DR=".env.dr"
PROJECT_WIP="mnfst"
PROJECT_DR="mnfst-dr"
DR_PORT=2100

red()   { printf '\033[1;31m%s\033[0m\n' "$*"; }
green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[1;33m%s\033[0m\n' "$*"; }
dim()   { printf '\033[2m%s\033[0m\n' "$*"; }

# ── Helpers ────────────────────────────────────────────────────────────────

get_tailscale_ip() {
  tailscale ip -4 2>/dev/null || echo ""
}

ensure_env() {
  # Create .env.dr if missing
  if [[ ! -f "$ENV_DR" ]]; then
    cat > "$ENV_DR" <<'EOF'
# Auto-generated by disaster-recovery.sh
BETTER_AUTH_SECRET=
EOF
  fi

  if ! grep -qE '^BETTER_AUTH_SECRET=.+' "$ENV_DR" 2>/dev/null; then
    yellow "⚠  .env.dr missing BETTER_AUTH_SECRET."
    local secret
    secret=$(openssl rand -hex 32)
    if grep -qE '^BETTER_AUTH_SECRET=$' "$ENV_DR" 2>/dev/null; then
      sed -i "s/^BETTER_AUTH_SECRET=$/BETTER_AUTH_SECRET=$secret/" "$ENV_DR"
    else
      echo "BETTER_AUTH_SECRET=$secret" >> "$ENV_DR"
    fi
    green "✓  Generated BETTER_AUTH_SECRET"
  fi
}

stop_project() {
  local project="$1" compose="$2"
  if docker compose -f "$compose" -p "$project" ps --quiet 2>/dev/null | grep -q .; then
    yellow "⏹  Stopping $project..."
    docker compose -f "$compose" -p "$project" down --remove-orphans 2>/dev/null || true
    green "✓  $project stopped"
  else
    dim "   $project not running"
  fi
}

start_dr() {
  ensure_env

  local ts_ip
  ts_ip=$(get_tailscale_ip)
  if [[ -z "$ts_ip" ]]; then
    red "✗  Tailscale not running. Start it first: sudo tailscale up"
    exit 1
  fi

  green "🚀  Starting DR stack (mnfst-dr)..."
  docker compose -f "$COMPOSE_DR" --env-file "$ENV_DR" up -d

  echo ""
  green "✓  DR stack is up"
  echo ""
  dim "   Dashboard:  http://${ts_ip}:${DR_PORT}"
  dim "   Project:    $PROJECT_DR"
  dim "   Image:      manifestdotbuild/manifest:latest"
  echo ""
}

# ── Commands ───────────────────────────────────────────────────────────────

cmd_status() {
  echo ""
  yellow "── WIP stack ($PROJECT_WIP) ──"
  docker compose -f "$COMPOSE_WIP" -p "$PROJECT_WIP" ps 2>/dev/null || dim "   not running"
  echo ""
  yellow "── DR stack ($PROJECT_DR) ──"
  docker compose -f "$COMPOSE_DR" -p "$PROJECT_DR" --env-file "$ENV_DR" ps 2>/dev/null || dim "   not running"
  echo ""
  local ts_ip
  ts_ip=$(get_tailscale_ip)
  if [[ -n "$ts_ip" ]]; then
    dim "   Tailscale IP: ${ts_ip}"
  fi
  echo ""
}

cmd_stop() {
  stop_project "$PROJECT_DR" "$COMPOSE_DR"
}

cmd_restore() {
  stop_project "$PROJECT_DR" "$COMPOSE_DR"
  echo ""
  green "🔄  Starting WIP stack (mnfst)..."
  docker compose -f "$COMPOSE_WIP" -p "$PROJECT_WIP" up -d
  green "✓  WIP stack restored"
}

cmd_default() {
  stop_project "$PROJECT_WIP" "$COMPOSE_WIP"
  echo ""
  start_dr
}

# ── Main ───────────────────────────────────────────────────────────────────

case "${1:-}" in
  status)  cmd_status ;;
  stop)    cmd_stop ;;
  restore) cmd_restore ;;
  ""|-*)   cmd_default ;;
  *)
    red "Unknown command: $1"
    echo "Usage: $0 [status|stop|restore]"
    exit 1
    ;;
esac
