openapi: 3.0.3
info:
  title: Link Node API Contracts
  description: |
    API contracts for the Link output node feature.

    The Link node is primarily a client-side action (calling window.openai.openExternal),
    but this document defines:
    1. The connection validation API enhancement for Link node constraints
    2. The node execution output structure
  version: 1.0.0

paths:
  /api/flows/{flowId}/validate:
    get:
      summary: Validate flow connections
      description: |
        Validates all connections in a flow, including Link node source constraints.

        **Link Node Constraint**: Link nodes can only accept connections from
        `interface` category nodes (e.g., StatCard). Connections from other
        categories will return validation errors.
      operationId: validateFlowConnections
      tags:
        - Schema Validation
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The flow ID to validate
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlowValidationResponse'
              examples:
                validFlow:
                  summary: Valid flow with Link node
                  value:
                    flowId: "550e8400-e29b-41d4-a716-446655440000"
                    status: "valid"
                    summary:
                      total: 2
                      compatible: 2
                      warnings: 0
                      errors: 0
                      unknown: 0
                    connections:
                      - connectionId: "conn-1"
                        sourceNodeId: "user-intent-1"
                        targetNodeId: "stat-card-1"
                        status: "compatible"
                        issues: []
                      - connectionId: "conn-2"
                        sourceNodeId: "stat-card-1"
                        targetNodeId: "link-1"
                        status: "compatible"
                        issues: []
                invalidLinkSource:
                  summary: Invalid Link node connection
                  value:
                    flowId: "550e8400-e29b-41d4-a716-446655440000"
                    status: "errors"
                    summary:
                      total: 2
                      compatible: 1
                      warnings: 0
                      errors: 1
                      unknown: 0
                    connections:
                      - connectionId: "conn-1"
                        sourceNodeId: "user-intent-1"
                        targetNodeId: "api-call-1"
                        status: "compatible"
                        issues: []
                      - connectionId: "conn-2"
                        sourceNodeId: "api-call-1"
                        targetNodeId: "link-1"
                        status: "error"
                        issues:
                          - type: "constraint-violation"
                            message: "Link nodes can only be connected after UI nodes"
                            severity: "error"
        '404':
          description: Flow not found

components:
  schemas:
    # ==========================================================================
    # Link Node Types
    # ==========================================================================

    LinkNodeParameters:
      type: object
      description: Configuration parameters for a Link node
      required:
        - href
      properties:
        href:
          type: string
          description: |
            URL to open. Can be:
            - Static URL: "https://example.com"
            - Template with variables: "{{api_call.body.redirectUrl}}"
          example: "https://docs.example.com/guide"

    LinkNodeOutput:
      type: object
      description: Output produced by Link node execution
      required:
        - type
        - href
      properties:
        type:
          type: string
          enum: [link]
          description: Discriminator indicating this is a link action
        href:
          type: string
          format: uri
          description: Resolved URL after template variable substitution
          example: "https://docs.example.com/guide"

    LinkNodeInstance:
      type: object
      description: A Link node instance within a flow
      required:
        - id
        - slug
        - type
        - name
        - position
        - parameters
      properties:
        id:
          type: string
          format: uuid
        slug:
          type: string
          description: Human-readable identifier (e.g., "link_1")
        type:
          type: string
          enum: [Link]
        name:
          type: string
          description: Display name for the node
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          $ref: '#/components/schemas/LinkNodeParameters'

    # ==========================================================================
    # Validation Types
    # ==========================================================================

    FlowValidationResponse:
      type: object
      required:
        - flowId
        - status
        - summary
        - connections
      properties:
        flowId:
          type: string
          format: uuid
        status:
          type: string
          enum: [valid, warnings, errors]
        summary:
          $ref: '#/components/schemas/ValidationSummary'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/ConnectionValidationResult'
        nodeErrors:
          type: array
          items:
            $ref: '#/components/schemas/NodeValidationError'

    ValidationSummary:
      type: object
      required:
        - total
        - compatible
        - warnings
        - errors
        - unknown
      properties:
        total:
          type: integer
        compatible:
          type: integer
        warnings:
          type: integer
        errors:
          type: integer
        unknown:
          type: integer

    ConnectionValidationResult:
      type: object
      required:
        - connectionId
        - sourceNodeId
        - targetNodeId
        - status
        - issues
      properties:
        connectionId:
          type: string
        sourceNodeId:
          type: string
        targetNodeId:
          type: string
        status:
          type: string
          enum: [compatible, warning, error, unknown]
        issues:
          type: array
          items:
            $ref: '#/components/schemas/CompatibilityIssue'

    CompatibilityIssue:
      type: object
      required:
        - type
        - message
      properties:
        type:
          type: string
          enum:
            - type-mismatch
            - missing-field
            - constraint-violation
          description: |
            Issue type. New `constraint-violation` type added for Link node
            source category validation.
        message:
          type: string
        severity:
          type: string
          enum: [warning, error]

    NodeValidationError:
      type: object
      required:
        - nodeId
        - nodeType
        - errorCode
        - message
      properties:
        nodeId:
          type: string
        nodeType:
          type: string
        errorCode:
          type: string
        message:
          type: string

    # ==========================================================================
    # Common Types
    # ==========================================================================

    Position:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: number
        y:
          type: number

    # ==========================================================================
    # Node Type Definition (Registry)
    # ==========================================================================

    LinkNodeTypeDefinition:
      type: object
      description: |
        Node type definition for Link node as registered in the node type registry.
        This defines the static configuration, not instance data.
      properties:
        name:
          type: string
          const: Link
        displayName:
          type: string
          const: Open Link
        icon:
          type: string
          const: external-link
        group:
          type: array
          items:
            type: string
          example: [flow, output]
        category:
          type: string
          enum: [return]
          description: Return category indicates terminal/output node
        description:
          type: string
          const: Open an external URL in the user's browser. Terminates the flow.
        inputs:
          type: array
          items:
            type: string
          example: [main]
        outputs:
          type: array
          items:
            type: string
          example: []
          description: Empty array - Link nodes are terminal (no downstream connections)
        defaultParameters:
          $ref: '#/components/schemas/LinkNodeParameters'
        inputSchema:
          type: object
          description: Accepts any input data for template variable resolution
        outputSchema:
          type: 'null'
          description: Terminal nodes have no output schema
