openapi: 3.0.3
info:
  title: Nodes API
  description: API for managing flow nodes and connections
  version: 1.0.0

servers:
  - url: /api
    description: Local development server

paths:
  # ============================================================================
  # Flow Nodes Operations
  # ============================================================================
  /flows/{flowId}/nodes:
    get:
      summary: Get all nodes in a flow
      tags: [Nodes]
      parameters:
        - $ref: '#/components/parameters/flowId'
      responses:
        '200':
          description: List of nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeInstance'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Add a new node to a flow
      tags: [Nodes]
      parameters:
        - $ref: '#/components/parameters/flowId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNodeRequest'
      responses:
        '201':
          description: Node created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /flows/{flowId}/nodes/{nodeId}:
    get:
      summary: Get a specific node
      tags: [Nodes]
      parameters:
        - $ref: '#/components/parameters/flowId'
        - $ref: '#/components/parameters/nodeId'
      responses:
        '200':
          description: Node details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update a node
      tags: [Nodes]
      parameters:
        - $ref: '#/components/parameters/flowId'
        - $ref: '#/components/parameters/nodeId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNodeRequest'
      responses:
        '200':
          description: Node updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a node (and its connections)
      tags: [Nodes]
      parameters:
        - $ref: '#/components/parameters/flowId'
        - $ref: '#/components/parameters/nodeId'
      responses:
        '204':
          description: Node deleted
        '404':
          $ref: '#/components/responses/NotFound'

  /flows/{flowId}/nodes/{nodeId}/position:
    patch:
      summary: Update node position only
      description: Optimized endpoint for canvas drag operations
      tags: [Nodes]
      parameters:
        - $ref: '#/components/parameters/flowId'
        - $ref: '#/components/parameters/nodeId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePositionRequest'
      responses:
        '200':
          description: Position updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'
        '404':
          $ref: '#/components/responses/NotFound'

  /flows/{flowId}/nodes/batch-position:
    patch:
      summary: Update multiple node positions at once
      description: Batch endpoint for efficiency when moving multiple nodes
      tags: [Nodes]
      parameters:
        - $ref: '#/components/parameters/flowId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BatchPositionUpdate'
      responses:
        '200':
          description: Positions updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeInstance'

  # ============================================================================
  # Flow Connections Operations
  # ============================================================================
  /flows/{flowId}/connections:
    get:
      summary: Get all connections in a flow
      tags: [Connections]
      parameters:
        - $ref: '#/components/parameters/flowId'
      responses:
        '200':
          description: List of connections
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connection'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Create a new connection
      tags: [Connections]
      parameters:
        - $ref: '#/components/parameters/flowId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConnectionRequest'
      responses:
        '201':
          description: Connection created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connection'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /flows/{flowId}/connections/{connectionId}:
    delete:
      summary: Delete a connection
      tags: [Connections]
      parameters:
        - $ref: '#/components/parameters/flowId'
        - $ref: '#/components/parameters/connectionId'
      responses:
        '204':
          description: Connection deleted
        '404':
          $ref: '#/components/responses/NotFound'

  # ============================================================================
  # Node Types (from nodes package)
  # ============================================================================
  /node-types:
    get:
      summary: Get all available node types
      tags: [Node Types]
      responses:
        '200':
          description: List of node type definitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeTypeInfo'

  /node-types/{typeName}:
    get:
      summary: Get a specific node type definition
      tags: [Node Types]
      parameters:
        - name: typeName
          in: path
          required: true
          schema:
            type: string
          example: Interface
      responses:
        '200':
          description: Node type definition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeTypeInfo'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  # ==========================================================================
  # Parameters
  # ==========================================================================
  parameters:
    flowId:
      name: flowId
      in: path
      required: true
      description: Flow UUID
      schema:
        type: string
        format: uuid

    nodeId:
      name: nodeId
      in: path
      required: true
      description: Node UUID
      schema:
        type: string
        format: uuid

    connectionId:
      name: connectionId
      in: path
      required: true
      description: Connection UUID
      schema:
        type: string
        format: uuid

  # ==========================================================================
  # Schemas
  # ==========================================================================
  schemas:
    # Node Instance
    NodeInstance:
      type: object
      required: [id, type, name, position, parameters]
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier within the flow
        type:
          type: string
          enum: [Interface, Return, CallFlow]
          description: Node type name
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Display name (unique within flow)
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          type: object
          description: Type-specific configuration
          additionalProperties: true

    # Position
    Position:
      type: object
      required: [x, y]
      properties:
        x:
          type: number
          description: X coordinate on canvas
        y:
          type: number
          description: Y coordinate on canvas

    # Connection
    Connection:
      type: object
      required: [id, sourceNodeId, sourceHandle, targetNodeId, targetHandle]
      properties:
        id:
          type: string
          format: uuid
        sourceNodeId:
          type: string
          format: uuid
          description: ID of source node
        sourceHandle:
          type: string
          description: Handle identifier on source (e.g., 'action:submit', 'right')
        targetNodeId:
          type: string
          format: uuid
          description: ID of target node
        targetHandle:
          type: string
          description: Handle identifier on target (e.g., 'left')

    # Node Type Info (from nodes package)
    NodeTypeInfo:
      type: object
      required: [name, displayName, icon, group, description, inputs, outputs]
      properties:
        name:
          type: string
          description: Internal type identifier
        displayName:
          type: string
          description: Human-readable name
        icon:
          type: string
          description: Lucide icon name
        group:
          type: array
          items:
            type: string
          description: Category tags
        description:
          type: string
          description: Human-readable description
        inputs:
          type: array
          items:
            type: string
          description: Input handle types
        outputs:
          type: array
          items:
            type: string
          description: Output handle types
        defaultParameters:
          type: object
          additionalProperties: true
          description: Default values for node parameters

    # Request Bodies
    CreateNodeRequest:
      type: object
      required: [type, name, position]
      properties:
        type:
          type: string
          enum: [Interface, Return, CallFlow]
        name:
          type: string
          minLength: 1
          maxLength: 100
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          type: object
          additionalProperties: true
          description: Initial parameters (defaults applied if not provided)

    UpdateNodeRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          type: object
          additionalProperties: true

    UpdatePositionRequest:
      type: object
      required: [x, y]
      properties:
        x:
          type: number
        y:
          type: number

    BatchPositionUpdate:
      type: object
      required: [nodeId, position]
      properties:
        nodeId:
          type: string
          format: uuid
        position:
          $ref: '#/components/schemas/Position'

    CreateConnectionRequest:
      type: object
      required: [sourceNodeId, sourceHandle, targetNodeId, targetHandle]
      properties:
        sourceNodeId:
          type: string
          format: uuid
        sourceHandle:
          type: string
        targetNodeId:
          type: string
          format: uuid
        targetHandle:
          type: string

  # ==========================================================================
  # Responses
  # ==========================================================================
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              statusCode:
                type: integer
                example: 404

    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              error:
                type: string
              statusCode:
                type: integer
                example: 400

tags:
  - name: Nodes
    description: Operations for managing nodes within a flow
  - name: Connections
    description: Operations for managing connections between nodes
  - name: Node Types
    description: Query available node type definitions
