import type { Metadata } from 'next'
import {
  getBlockDescription,
  getBlockName,
  getCategoryName
} from '@/lib/og-image-utils'

export async function generateMetadata({
  params
}: {
  params: Promise<{ category: string; block: string }>
}): Promise<Metadata> {
  const { category, block } = await params

  const blockName = getBlockName(block)
  const categoryName = getCategoryName(category)
  const blockDescription = getBlockDescription(block, blockName)

  const fullTitle = `${blockName} shadcn/ui block for ChatGPT Apps | Manifest UI`
  const description = `${blockName} (${categoryName}): ${blockDescription}`

  // Preview image URL - generated by the preview generation workflow
  const previewImageUrl = `https://ui.manifest.build/previews/${block}.png`

  return {
    title: fullTitle,
    description,
    keywords: [
      blockName,
      categoryName,
      'React component',
      'ChatGPT UI',
      'shadcn',
      'agentic UI',
      'MCP apps'
    ],
    alternates: {
      canonical: `/blocks/${category}/${block}`
    },
    openGraph: {
      title: fullTitle,
      description,
      url: `https://ui.manifest.build/blocks/${category}/${block}`,
      type: 'website',
      siteName: 'Manifest UI',
      images: [
        {
          url: previewImageUrl,
          width: 1200,
          height: 630,
          alt: `${blockName} component preview`
        }
      ]
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [previewImageUrl]
    }
  }
}

export default function BlockLayout({
  children
}: {
  children: React.ReactNode
}) {
  return children
}
