openapi: 3.0.3
info:
  title: Authentication API
  description: |
    Authentication endpoints for user login, signup, logout, and session management.
    Uses better-auth library which handles most auth endpoints automatically.
  version: 1.0.0

servers:
  - url: http://localhost:3847/api
    description: Development server

paths:
  /auth/sign-up/email:
    post:
      summary: Register a new user
      description: Creates a new user account with email and password
      operationId: signUp
      tags:
        - Authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Validation error or email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/sign-in/email:
    post:
      summary: Authenticate user
      description: Authenticates user with email and password, creates session
      operationId: signIn
      tags:
        - Authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Authentication successful
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/sign-out:
    post:
      summary: End user session
      description: Invalidates the current session and clears cookies
      operationId: signOut
      tags:
        - Authentication
      responses:
        '200':
          description: Logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true

  /auth/session:
    get:
      summary: Get current session
      description: Returns the current user session if authenticated
      operationId: getSession
      tags:
        - Authentication
      responses:
        '200':
          description: Current session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    SignUpRequest:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 4
          example: secretpassword
        name:
          type: string
          example: John Doe

    SignInRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: admin@manifest.build
        password:
          type: string
          example: admin

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        session:
          $ref: '#/components/schemas/Session'

    SessionResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        session:
          $ref: '#/components/schemas/Session'

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        emailVerified:
          type: boolean
        image:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Session:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        expiresAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
        status:
          type: integer

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: better-auth.session_token

security:
  - cookieAuth: []
