openapi: 3.0.3
info:
  title: User Management API
  description: |
    API endpoints for managing user access to apps.
    Only accessible by app owners and admins.

    **Security Note**: For privacy, unauthorized access to resources returns 404 (Not Found)
    instead of 403 (Forbidden) to prevent information leakage about resource existence.
  version: 1.0.0

servers:
  - url: http://localhost:3847/api
    description: Development server

paths:
  /apps/{appId}/users:
    get:
      summary: List users with access to app
      description: Returns all users who have access to this app with their roles
      operationId: listAppUsers
      tags:
        - User Management
      parameters:
        - $ref: '#/components/parameters/appId'
      responses:
        '200':
          description: List of users with access
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppUser'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: |
            App not found OR user does not have access to this app.
            Returns 404 in both cases to prevent information leakage.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Add user to app
      description: |
        Grants a user access to the app with the specified role.
        The user must already have an account in the system.
      operationId: addUserToApp
      tags:
        - User Management
      parameters:
        - $ref: '#/components/parameters/appId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUserRequest'
      responses:
        '201':
          description: User added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppUser'
        '400':
          description: |
            Validation error. Possible reasons:
            - User not found (email not registered)
            - User already has access to this app
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: |
            App not found OR user does not have access to this app.
            Returns 404 in both cases to prevent information leakage.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /apps/{appId}/users/{userId}:
    delete:
      summary: Remove user from app
      description: |
        Revokes a user's access to the app.
        Cannot remove the owner of the app.
      operationId: removeUserFromApp
      tags:
        - User Management
      parameters:
        - $ref: '#/components/parameters/appId'
        - $ref: '#/components/parameters/userId'
      responses:
        '204':
          description: User removed successfully
        '400':
          description: Cannot remove owner
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: |
            App not found, user not in app, OR current user does not have access.
            Returns 404 in all cases to prevent information leakage.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/me:
    get:
      summary: Get current user profile
      description: Returns the currently authenticated user's profile
      operationId: getCurrentUser
      tags:
        - Users
      responses:
        '200':
          description: Current user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/search:
    get:
      summary: Search users by email
      description: Search for users by email to add to an app
      operationId: searchUsers
      tags:
        - Users
      parameters:
        - name: email
          in: query
          required: true
          description: Email to search for (exact match)
          schema:
            type: string
            format: email
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    appId:
      name: appId
      in: path
      required: true
      description: The app ID
      schema:
        type: string
        format: uuid

    userId:
      name: userId
      in: path
      required: true
      description: The user ID
      schema:
        type: string
        format: uuid

  schemas:
    AppUser:
      type: object
      description: A user with access to an app
      properties:
        id:
          type: string
          format: uuid
          description: User ID
        email:
          type: string
          format: email
        name:
          type: string
          nullable: true
        role:
          $ref: '#/components/schemas/AppRole'
        isOwner:
          type: boolean
          description: Whether this user is the owner (cannot be removed)
        createdAt:
          type: string
          format: date-time
          description: When the user was granted access
      required:
        - id
        - email
        - role
        - isOwner

    AddUserRequest:
      type: object
      required:
        - email
        - role
      properties:
        email:
          type: string
          format: email
          description: Email of the user to add (must already exist)
          example: newuser@example.com
        role:
          $ref: '#/components/schemas/AppRole'

    AppRole:
      type: string
      enum:
        - owner
        - admin
      description: |
        User role for the app:
        - owner: Full access, cannot be removed
        - admin: Full access, can be removed by owner or other admins

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
          nullable: true
        image:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: User not found
        code:
          type: string
          example: USER_NOT_FOUND
        status:
          type: integer
          example: 404

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: better-auth.session_token

security:
  - cookieAuth: []
