openapi: 3.0.3
info:
  title: Navigation Sidebar API
  description: API endpoints for the navigation sidebar feature
  version: 1.0.0

servers:
  - url: /api
    description: Backend API

paths:
  /flows:
    get:
      summary: Get all flows
      description: |
        Returns all flows across all apps with their parent app data included.
        Used by the Flows page in the sidebar navigation.
      operationId: getAllFlows
      tags:
        - Flows
      responses:
        '200':
          description: List of all flows with parent app context
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FlowWithApp'
              example:
                - id: "550e8400-e29b-41d4-a716-446655440000"
                  appId: "123e4567-e89b-12d3-a456-426614174000"
                  name: "Get Customer Orders"
                  description: "Retrieves order history for a customer"
                  toolName: "getCustomerOrders"
                  toolDescription: "Fetch all orders for a given customer ID"
                  isActive: true
                  createdAt: "2025-12-27T10:00:00Z"
                  updatedAt: "2025-12-27T10:00:00Z"
                  app:
                    id: "123e4567-e89b-12d3-a456-426614174000"
                    name: "E-Commerce App"
                    slug: "e-commerce-app"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Flow:
      type: object
      required:
        - id
        - appId
        - name
        - toolName
        - toolDescription
        - isActive
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the flow
        appId:
          type: string
          format: uuid
          description: ID of the parent app
        name:
          type: string
          maxLength: 100
          description: Display name for the flow
        description:
          type: string
          maxLength: 500
          description: Optional description of the flow
        toolName:
          type: string
          maxLength: 100
          description: MCP tool name
        toolDescription:
          type: string
          maxLength: 500
          description: Description for the MCP tool
        isActive:
          type: boolean
          description: Whether the flow is active
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    AppSummary:
      type: object
      required:
        - id
        - name
        - slug
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the app
        name:
          type: string
          description: Display name for the app
        slug:
          type: string
          description: URL-friendly identifier

    FlowWithApp:
      allOf:
        - $ref: '#/components/schemas/Flow'
        - type: object
          required:
            - app
          properties:
            app:
              $ref: '#/components/schemas/AppSummary'
              description: Parent app information

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
        statusCode:
          type: integer
          description: HTTP status code
