#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const [baseFile, headFile] = process.argv.slice(2);
if (!baseFile || !headFile) {
  console.error('Usage: render-diagram.cjs <base.json> <head.json>');
  process.exit(1);
}

const base = JSON.parse(fs.readFileSync(baseFile, 'utf8'));
const head = JSON.parse(fs.readFileSync(headFile, 'utf8'));

const baseNames = new Set(Object.keys(base.tables));
const headNames = new Set(Object.keys(head.tables));

const addedTables = [...headNames].filter((n) => !baseNames.has(n)).sort();
const droppedTables = [...baseNames].filter((n) => !headNames.has(n)).sort();
const sharedTables = [...headNames].filter((n) => baseNames.has(n));

const modifiedTables = [];
for (const name of sharedTables) {
  const changes = diffTable(base.tables[name], head.tables[name]);
  if (changes.length > 0) modifiedTables.push({ name, changes });
}
modifiedTables.sort((a, b) => a.name.localeCompare(b.name));

const modifiedMap = new Map(modifiedTables.map((m) => [m.name, m.changes]));
const noSchemaChanges = !addedTables.length && !modifiedTables.length && !droppedTables.length;

const mermaid = buildMermaid(head, base, addedTables, modifiedMap, droppedTables);
const summaryBlock = buildSummary(addedTables, modifiedTables, droppedTables);
const detailsBlock = buildDetails(head, addedTables, modifiedTables, droppedTables);

const migrationFiles = (process.env.MIGRATION_FILES || '')
  .split('\n')
  .map((f) => f.trim())
  .filter(Boolean);
const migrationList = migrationFiles.length
  ? migrationFiles.map((f) => `- \`${path.basename(f)}\``).join('\n')
  : '_(no migration files detected in this PR)_';

const body = `<!-- db-diagram-bot -->
## Database schema changes

**Migrations in this PR:**
${migrationList}

### Summary
${summaryBlock}
${
  noSchemaChanges
    ? ''
    : `
### Schema diagram

Showing only changed tables. 🟢 added, 🟡 modified, 🔴 removed. Changed columns are annotated inline.

\`\`\`mermaid
${mermaid}
\`\`\`

<details>
<summary>Detailed column-level changes</summary>

${detailsBlock}
</details>`
}

---
<sub>Generated by the <code>db-diagram</code> workflow • only tables with schema changes are shown.</sub>
`;

process.stdout.write(body);

function diffTable(a, b) {
  const changes = [];
  const aCols = new Map(a.columns.map((c) => [c.name, c]));
  const bCols = new Map(b.columns.map((c) => [c.name, c]));
  for (const [name, col] of bCols) {
    const before = aCols.get(name);
    if (!before) {
      changes.push({ kind: 'added', column: name, type: col.type, nullable: col.nullable });
    } else if (before.type !== col.type || before.nullable !== col.nullable) {
      changes.push({ kind: 'modified', column: name, from: before, to: col });
    }
  }
  for (const [name, col] of aCols) {
    if (!bCols.has(name)) {
      changes.push({ kind: 'dropped', column: name, type: col.type });
    }
  }

  const aPk = new Set(a.primaryKeys || []);
  const bPk = new Set(b.primaryKeys || []);
  const pkAdded = [...bPk].filter((c) => !aPk.has(c));
  const pkDropped = [...aPk].filter((c) => !bPk.has(c));
  if (pkAdded.length || pkDropped.length) {
    changes.push({ kind: 'pk-changed', added: pkAdded, dropped: pkDropped });
  }

  const fkKey = (fk) => `${fk.column}->${fk.toTable}.${fk.toColumn}`;
  const aFk = new Map((a.foreignKeys || []).map((fk) => [fkKey(fk), fk]));
  const bFk = new Map((b.foreignKeys || []).map((fk) => [fkKey(fk), fk]));
  for (const [k, fk] of bFk) {
    if (!aFk.has(k)) changes.push({ kind: 'fk-added', fk });
  }
  for (const [k, fk] of aFk) {
    if (!bFk.has(k)) changes.push({ kind: 'fk-dropped', fk });
  }

  return changes;
}

function buildMermaid(headSnap, baseSnap, added, modMap, dropped) {
  const lines = ['erDiagram'];
  const addedSet = new Set(added);
  const droppedSet = new Set(dropped);
  const rendered = new Set();

  const changedNames = [...added, ...modMap.keys(), ...dropped].sort();

  for (const name of changedNames) {
    const isAdded = addedSet.has(name);
    const isDropped = droppedSet.has(name);
    const isModified = !isAdded && !isDropped;
    const snap = isDropped ? baseSnap : headSnap;
    const table = snap.tables[name];
    if (!table) continue;

    let header;
    if (isAdded) header = `    ${name}["🟢 ${name} (added)"] {`;
    else if (isDropped) header = `    ${name}["🔴 ${name} (removed)"] {`;
    else header = `    ${name}["🟡 ${name} (modified)"] {`;
    lines.push(header);

    const changes = modMap.get(name) || [];
    const addedCols = new Set(
      changes.filter((c) => c.kind === 'added').map((c) => c.column),
    );
    const modCols = new Set(
      changes.filter((c) => c.kind === 'modified').map((c) => c.column),
    );
    const fkAddedCols = new Set(
      changes.filter((c) => c.kind === 'fk-added').map((c) => c.fk.column),
    );
    const fkDroppedCols = new Set(
      changes.filter((c) => c.kind === 'fk-dropped').map((c) => c.fk.column),
    );
    const pkChange = changes.find((c) => c.kind === 'pk-changed');
    const pkChangedCols = new Set(
      pkChange ? [...pkChange.added, ...pkChange.dropped] : [],
    );
    const droppedCols = changes.filter((c) => c.kind === 'dropped');

    for (const col of table.columns) {
      const safeType = sanitizeMermaidType(col.type);
      const pk = table.primaryKeys.includes(col.name) ? ' PK' : '';
      const fk = !pk && table.foreignKeys.some((f) => f.column === col.name) ? ' FK' : '';
      const note = isModified
        ? columnNote(col.name, {
            addedCols,
            modCols,
            fkAddedCols,
            fkDroppedCols,
            pkChangedCols,
          })
        : '';
      lines.push(`        ${safeType} ${col.name}${pk}${fk}${note}`);
    }
    // Columns removed by this PR no longer exist in the head snapshot, so render
    // them as trailing rows (with their pre-drop type) flagged 🔴 removed.
    for (const c of droppedCols) {
      lines.push(`        ${sanitizeMermaidType(c.type)} ${c.column} "🔴 removed"`);
    }
    lines.push('    }');
    rendered.add(name);
  }

  for (const name of changedNames) {
    if (droppedSet.has(name)) continue;
    const table = headSnap.tables[name];
    if (!table) continue;
    for (const fk of table.foreignKeys) {
      if (!rendered.has(fk.toTable)) continue;
      lines.push(`    ${name} }o--|| ${fk.toTable} : "${fk.column}"`);
    }
  }

  return lines.join('\n');
}

// Builds the inline annotation for a single column of a modified table.
// 🟢 for a newly added column, 🟡 for any in-place change (type/nullable, FK,
// or PK membership). Dropped columns are annotated separately as trailing rows.
function columnNote(colName, sets) {
  if (sets.addedCols.has(colName)) return ' "🟢 added"';
  const parts = [];
  if (sets.modCols.has(colName)) parts.push('modified');
  if (sets.fkAddedCols.has(colName)) parts.push('FK added');
  if (sets.fkDroppedCols.has(colName)) parts.push('FK removed');
  if (sets.pkChangedCols.has(colName)) parts.push('PK changed');
  if (!parts.length) return '';
  return ` "🟡 ${parts.join(', ')}"`;
}

function buildSummary(added, modified, dropped) {
  const lines = [];
  if (added.length) {
    lines.push(`- 🟢 **Added tables:** ${added.map((n) => `\`${n}\``).join(', ')}`);
  }
  if (modified.length) {
    lines.push(
      `- 🟡 **Modified tables:** ${modified
        .map((m) => `\`${m.name}\` (${describeChanges(m.changes)})`)
        .join(', ')}`,
    );
  }
  if (dropped.length) {
    lines.push(`- 🔴 **Removed tables:** ${dropped.map((n) => `\`${n}\``).join(', ')}`);
  }
  if (!lines.length) {
    return '_No schema changes detected — migration files were touched but the resulting schema is identical to `main`._';
  }
  return lines.join('\n');
}

function describeChanges(changes) {
  const counts = {
    added: 0,
    modified: 0,
    dropped: 0,
    'fk-added': 0,
    'fk-dropped': 0,
    'pk-changed': 0,
  };
  for (const c of changes) counts[c.kind]++;
  const parts = [];
  if (counts.added) parts.push(`+${counts.added} col`);
  if (counts.modified) parts.push(`~${counts.modified} col`);
  if (counts.dropped) parts.push(`-${counts.dropped} col`);
  if (counts['fk-added']) parts.push(`+${counts['fk-added']} FK`);
  if (counts['fk-dropped']) parts.push(`-${counts['fk-dropped']} FK`);
  if (counts['pk-changed']) parts.push('PK changed');
  return parts.join(', ');
}

function buildDetails(snapshot, added, modified, dropped) {
  const out = [];
  for (const t of added) {
    out.push(`#### 🟢 \`${t}\` _(new table)_`);
    for (const col of snapshot.tables[t].columns) {
      const pk = snapshot.tables[t].primaryKeys.includes(col.name) ? ' **PK**' : '';
      const nullable = col.nullable ? 'NULL' : 'NOT NULL';
      out.push(`- \`${col.name}\` \`${col.type}\` ${nullable}${pk}`);
    }
    out.push('');
  }
  for (const { name, changes } of modified) {
    out.push(`#### 🟡 \`${name}\``);
    for (const c of changes) {
      if (c.kind === 'added') {
        out.push(`- ➕ added \`${c.column}\` \`${c.type}\` ${c.nullable ? 'NULL' : 'NOT NULL'}`);
      } else if (c.kind === 'modified') {
        const fromDesc = `\`${c.from.type}\` ${c.from.nullable ? 'NULL' : 'NOT NULL'}`;
        const toDesc = `\`${c.to.type}\` ${c.to.nullable ? 'NULL' : 'NOT NULL'}`;
        out.push(`- 🔄 modified \`${c.column}\`: ${fromDesc} → ${toDesc}`);
      } else if (c.kind === 'dropped') {
        out.push(`- ➖ dropped \`${c.column}\` _(was \`${c.type}\`)_`);
      } else if (c.kind === 'fk-added') {
        out.push(`- 🔗 added FK \`${c.fk.column}\` → \`${c.fk.toTable}.${c.fk.toColumn}\``);
      } else if (c.kind === 'fk-dropped') {
        out.push(`- 🔗 dropped FK \`${c.fk.column}\` → \`${c.fk.toTable}.${c.fk.toColumn}\``);
      } else if (c.kind === 'pk-changed') {
        const parts = [];
        if (c.added.length) parts.push(`+ \`${c.added.join(', ')}\``);
        if (c.dropped.length) parts.push(`- \`${c.dropped.join(', ')}\``);
        out.push(`- 🔑 primary key changed: ${parts.join(', ')}`);
      }
    }
    out.push('');
  }
  for (const t of dropped) {
    out.push(`#### 🔴 \`${t}\` _(removed)_`);
    out.push('');
  }
  return out.join('\n');
}

function sanitizeMermaidType(t) {
  return t.replace(/[^a-zA-Z0-9_]/g, '_');
}
