# Transform Node API Contracts
# OpenAPI 3.0 specification for transformer node endpoints

openapi: 3.0.3
info:
  title: Transform Node API
  version: 1.0.0
  description: API contracts for Transform node category operations

paths:
  /flows/{flowId}/nodes:
    post:
      summary: Add transformer node to flow
      operationId: addTransformerNode
      tags:
        - Nodes
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTransformerNodeRequest'
      responses:
        '201':
          description: Transformer node created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'
        '400':
          description: Invalid request (validation error)
        '404':
          description: Flow not found

  /flows/{flowId}/nodes/{nodeId}:
    patch:
      summary: Update transformer node configuration
      operationId: updateTransformerNode
      tags:
        - Nodes
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransformerNodeRequest'
      responses:
        '200':
          description: Node updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeInstance'
        '400':
          description: Invalid code (syntax error)
        '404':
          description: Flow or node not found

  /flows/{flowId}/validate-connection:
    post:
      summary: Validate connection compatibility
      operationId: validateConnection
      tags:
        - Schema
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateConnectionRequest'
      responses:
        '200':
          description: Compatibility result with suggestions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionValidationResult'

  /flows/{flowId}/insert-transformer:
    post:
      summary: Insert transformer between two nodes
      operationId: insertTransformer
      tags:
        - Nodes
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertTransformerRequest'
      responses:
        '201':
          description: Transformer inserted with connections established
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsertTransformerResponse'
        '400':
          description: Invalid request
        '404':
          description: Flow or nodes not found

  /flows/{flowId}/nodes/{nodeId}/test-transform:
    post:
      summary: Test transformation code with sample input
      operationId: testTransform
      tags:
        - Transform
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestTransformRequest'
      responses:
        '200':
          description: Transform result with inferred schema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestTransformResponse'
        '400':
          description: Code execution error

components:
  schemas:
    AddTransformerNodeRequest:
      type: object
      required:
        - type
        - name
        - position
      properties:
        type:
          type: string
          enum:
            - JavaScriptCodeTransform
        name:
          type: string
          minLength: 1
          maxLength: 100
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          $ref: '#/components/schemas/JavaScriptCodeTransformParameters'

    UpdateTransformerNodeRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        parameters:
          $ref: '#/components/schemas/JavaScriptCodeTransformParameters'
        position:
          $ref: '#/components/schemas/Position'

    JavaScriptCodeTransformParameters:
      type: object
      properties:
        code:
          type: string
          description: JavaScript transformation code
          default: 'return input;'
        resolvedOutputSchema:
          $ref: '#/components/schemas/JSONSchema'
          nullable: true

    ValidateConnectionRequest:
      type: object
      required:
        - sourceNodeId
        - targetNodeId
      properties:
        sourceNodeId:
          type: string
          format: uuid
        sourceHandle:
          type: string
          default: 'output'
        targetNodeId:
          type: string
          format: uuid
        targetHandle:
          type: string
          default: 'input'

    ConnectionValidationResult:
      type: object
      required:
        - status
        - issues
      properties:
        status:
          type: string
          enum:
            - compatible
            - warning
            - error
            - unknown
        issues:
          type: array
          items:
            $ref: '#/components/schemas/CompatibilityIssue'
        suggestedTransformers:
          type: array
          items:
            type: string
          description: Transformer types that could resolve incompatibility
        sourceSchema:
          $ref: '#/components/schemas/JSONSchema'
          nullable: true
        targetSchema:
          $ref: '#/components/schemas/JSONSchema'
          nullable: true

    CompatibilityIssue:
      type: object
      required:
        - type
        - message
        - severity
      properties:
        type:
          type: string
          enum:
            - missing_field
            - type_mismatch
            - format_mismatch
            - constraint_violation
        path:
          type: string
        message:
          type: string
        severity:
          type: string
          enum:
            - error
            - warning

    InsertTransformerRequest:
      type: object
      required:
        - transformerType
        - sourceNodeId
        - targetNodeId
      properties:
        transformerType:
          type: string
          enum:
            - JavaScriptCodeTransform
        sourceNodeId:
          type: string
          format: uuid
        targetNodeId:
          type: string
          format: uuid
        position:
          $ref: '#/components/schemas/Position'
          description: If not provided, calculated as midpoint between source and target

    InsertTransformerResponse:
      type: object
      required:
        - transformerNode
        - connections
      properties:
        transformerNode:
          $ref: '#/components/schemas/NodeInstance'
        connections:
          type: array
          items:
            $ref: '#/components/schemas/Connection'
          minItems: 2
          maxItems: 2

    TestTransformRequest:
      type: object
      required:
        - code
        - sampleInput
      properties:
        code:
          type: string
        sampleInput:
          type: object
          additionalProperties: true

    TestTransformResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        output:
          type: object
          additionalProperties: true
        inferredSchema:
          $ref: '#/components/schemas/JSONSchema'
        error:
          type: string

    NodeInstance:
      type: object
      required:
        - id
        - type
        - name
        - position
        - parameters
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
        name:
          type: string
        position:
          $ref: '#/components/schemas/Position'
        parameters:
          type: object
          additionalProperties: true

    Connection:
      type: object
      required:
        - id
        - sourceNodeId
        - sourceHandle
        - targetNodeId
        - targetHandle
      properties:
        id:
          type: string
          format: uuid
        sourceNodeId:
          type: string
          format: uuid
        sourceHandle:
          type: string
        targetNodeId:
          type: string
          format: uuid
        targetHandle:
          type: string

    Position:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: number
        y:
          type: number

    JSONSchema:
      type: object
      description: JSON Schema draft-07 compatible schema
      additionalProperties: true
