openapi: 3.0.3
info:
  title: App Invitations API
  description: API endpoints for managing app user invitations
  version: 1.0.0

servers:
  - url: /api
    description: API base path

tags:
  - name: Invitations
    description: App invitation management
  - name: Acceptance
    description: Invitation acceptance flow

paths:
  /apps/{appId}/invitations:
    get:
      summary: List pending invitations
      description: Returns all pending invitations for an app. Requires app access.
      tags: [Invitations]
      security:
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/AppId'
      responses:
        '200':
          description: List of pending invitations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PendingInvitation'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Create invitation
      description: |
        Creates a new invitation and sends invitation email.
        If user already exists, returns 400 suggesting direct add.
        If invitation already exists, returns 409 with existing invitation.
      tags: [Invitations]
      security:
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/AppId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvitationRequest'
      responses:
        '201':
          description: Invitation created and email sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingInvitation'
        '400':
          description: User already exists (use direct add instead)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                statusCode: 400
                message: "User already exists. Use direct add instead."
                userExists: true
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          description: Invitation already exists
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Error'
                  - type: object
                    properties:
                      existingInvitation:
                        $ref: '#/components/schemas/PendingInvitation'

  /apps/{appId}/invitations/{invitationId}:
    delete:
      summary: Revoke invitation
      description: Deletes a pending invitation, invalidating the invitation link.
      tags: [Invitations]
      security:
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/InvitationId'
      responses:
        '204':
          description: Invitation revoked successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /apps/{appId}/invitations/{invitationId}/resend:
    post:
      summary: Resend invitation email
      description: Sends the invitation email again with a new token.
      tags: [Invitations]
      security:
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/AppId'
        - $ref: '#/components/parameters/InvitationId'
      responses:
        '200':
          description: Invitation email resent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingInvitation'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /invitations/validate:
    get:
      summary: Validate invitation token
      description: |
        Validates an invitation token and returns invitation details.
        Used by frontend to display acceptance page before user authenticates.
      tags: [Acceptance]
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: Invitation token from email link
      responses:
        '200':
          description: Valid invitation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationValidation'
        '404':
          description: Invalid or expired invitation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                statusCode: 404
                message: "Invitation not found or has been revoked"

  /invitations/accept:
    post:
      summary: Accept invitation
      description: |
        Accepts an invitation for the authenticated user.
        - Validates token
        - Verifies user email matches invitation email
        - Creates UserAppRole entry
        - Deletes pending invitation
      tags: [Acceptance]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptInvitationRequest'
      responses:
        '200':
          description: Invitation accepted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptInvitationResponse'
        '400':
          description: Email mismatch or user already has access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Invitation not found or already accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /apps/{appId}/users:
    get:
      summary: List app users (updated)
      description: |
        Returns combined list of active users and pending invitations.
        Active users appear first, followed by pending invitations.
      tags: [Invitations]
      security:
        - cookieAuth: []
      parameters:
        - $ref: '#/components/parameters/AppId'
      responses:
        '200':
          description: Combined list of users and invitations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AppUserListItem'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: better-auth.session_token

  parameters:
    AppId:
      name: appId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: App identifier

    InvitationId:
      name: invitationId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Invitation identifier

  schemas:
    PendingInvitation:
      type: object
      required:
        - id
        - email
        - role
        - appId
        - invitedBy
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: Invitation ID
        email:
          type: string
          format: email
          description: Invited email address
        role:
          $ref: '#/components/schemas/AppRole'
        appId:
          type: string
          format: uuid
          description: Target app ID
        invitedBy:
          type: string
          format: uuid
          description: ID of user who sent invitation
        inviterName:
          type: string
          nullable: true
          description: Name of user who sent invitation
        createdAt:
          type: string
          format: date-time
          description: When invitation was created

    CreateInvitationRequest:
      type: object
      required:
        - email
        - role
      properties:
        email:
          type: string
          format: email
          description: Email address to invite
        role:
          $ref: '#/components/schemas/AppRole'

    AcceptInvitationRequest:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: Invitation token from email link

    AcceptInvitationResponse:
      type: object
      required:
        - success
        - appId
        - role
      properties:
        success:
          type: boolean
          example: true
        appId:
          type: string
          format: uuid
          description: App ID the user now has access to
        appName:
          type: string
          description: Name of the app
        role:
          $ref: '#/components/schemas/AppRole'
        message:
          type: string
          example: "Welcome! You now have access to My App."

    InvitationValidation:
      type: object
      required:
        - valid
        - email
        - appName
        - inviterName
      properties:
        valid:
          type: boolean
          example: true
        email:
          type: string
          format: email
          description: Email the invitation was sent to
        appId:
          type: string
          format: uuid
        appName:
          type: string
          description: Name of the app being invited to
        inviterName:
          type: string
          description: Name of person who sent invitation
        role:
          $ref: '#/components/schemas/AppRole'

    AppUserListItem:
      type: object
      required:
        - id
        - email
        - role
        - createdAt
        - status
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          $ref: '#/components/schemas/AppRole'
        createdAt:
          type: string
          format: date-time
        status:
          type: string
          enum: [active, pending]
          description: Whether this is an active user or pending invitation
        name:
          type: string
          nullable: true
          description: User's name (only for active users)
        isOwner:
          type: boolean
          description: Whether user is app owner (only for active users)
        invitedBy:
          type: string
          format: uuid
          description: ID of inviter (only for pending invitations)
        inviterName:
          type: string
          nullable: true
          description: Name of inviter (only for pending invitations)

    AppRole:
      type: string
      enum: [owner, admin]
      description: User role in the app

    Error:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            statusCode: 401
            message: "Unauthorized"

    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            statusCode: 403
            message: "You don't have permission to manage users for this app"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            statusCode: 404
            message: "App not found"
