export const CALENDAR_MANAGEMENT_KEYWORDS = [
  'schedule',
  'meeting',
  'calendar',
  'appointment',
  'availability',
  'time slot',
  'reschedule',
  'invite',
  'recurring',
  'agenda',
  'reminder',
  'block time',
  'free slot',
  'booking',
  'standup',
  'sync calendar',
  'calendly',
  'cal.com',
  'reclaim',
  'reclaim.ai',
  'clockwise',
  'motion',
  'google calendar',
  'focus time',
  'cancel',
  'room',
  'buffer',
  'timezone',
  'offsite',
  'sprint planning',
  'retrospective',
  'itinerary',
  'deadline',
  'morning routine',
  'lunch break',
  'office hours',
  'vacation',
  'holiday',
  'workout',
  'dentist',
  'haircut',
  'date night',
  'meal prep',
  'commute',
  'flight',
  'vet',
  'conference',
  'training',
  'onboarding',
  'catch up',
  'book a',
  'move the',
  'find a time',
  'check my',
  'add to calendar',
  'set up a',
  'plan a',
  'weekly sync',
  'daily standup',
  'team building',
  'time block',
  'next available',
  'side project',
  'graduation',
  'birthday party',
  'family visit',
  'networking event',
  'tax filing',
  'study group',
];
