/**
 * Complexity-scoring keywords. Each dimension maps to a weight in
 * `scoring/config.ts` — keywords push a message toward a higher (or lower)
 * complexity tier when matched.
 */
export const COMPLEXITY_KEYWORDS: Record<string, string[]> = {
  formalLogic: [
    'prove',
    'proof',
    'derive',
    'derivation',
    'theorem',
    'lemma',
    'corollary',
    'if and only if',
    'iff',
    'contradiction',
    'contrapositive',
    'induction',
    'deduction',
    'axiom',
    'postulate',
    'qed',
    'formally verify',
    'satisfiability',
    'soundness',
    'completeness',
    'undecidable',
    'reducible',
    'irrational',
    'rational',
    'conjecture',
    'hypothesis',
  ],

  analyticalReasoning: [
    'compare',
    'contrast',
    'evaluate',
    'assess',
    'trade-offs',
    'tradeoffs',
    'pros and cons',
    'advantages and disadvantages',
    'weigh',
    'critically analyze',
    'strengths and weaknesses',
    'implications',
    'ramifications',
    'nuance',
    'on the other hand',
    'counterargument',
    'analyze',
    'analysis',
    'explain',
  ],

  codeGeneration: [
    'write a function',
    'implement',
    'create a class',
    'build a component',
    'write code',
    'write a script',
    'code this',
    'program this',
    'create an api',
    'build a module',
    'scaffold',
    'boilerplate',
    'write a test',
    'write tests',
    'generate code',
    'component',
    'endpoint',
    'handler',
    'controller',
    'write a component',
    'create a component',
    'build a service',
    'implementing',
    'implemented',
    'implementation',
    'function',
    'method',
    'class',
    'variable',
    'array',
    'object',
    'loop',
    'syntax',
    'compile',
    'runtime',
    'parse',
    'import',
    'export',
    'module',
    'async',
    'await',
    'callback',
    'promise',
    'return',
    'parameter',
    'argument',
    'code',
    'coding',
    'script',
    'snippet',
    'console',
    'print',
    'output',
    'input',
    'string',
    'integer',
    'boolean',
    'null',
    'undefined',
    'type',
    'interface',
    'enum',
    'const',
    'let',
    'var',
    'def',
    'lambda',
    'for loop',
    'while loop',
    'if else',
    'try catch',
    'error handling',
    'unit test',
  ],

  codeReview: [
    'fix this bug',
    'debug',
    'why does this fail',
    'review this code',
    "what's wrong with",
    'code review',
    'refactor',
    'optimize this code',
    'find the error',
    'stack trace',
    'exception',
    'segfault',
    'memory leak',
    'race condition',
    'deadlock',
    'off by one',
    'typeerror',
    'referenceerror',
    'syntaxerror',
    'vulnerabilities',
    'vulnerability',
  ],

  technicalTerms: [
    'algorithm',
    'kubernetes',
    'distributed',
    'microservice',
    'database',
    'architecture',
    'infrastructure',
    'deployment',
    'pipeline',
    'middleware',
    'encryption',
    'authentication',
    'authorization',
    'latency',
    'throughput',
    'concurrency',
    'parallelism',
    'serialization',
    'deserialization',
    'react',
    'graphql',
    'typescript',
    'docker',
    'sql',
    'redis',
    'frontend',
    'backend',
    'server',
    'api',
    'oauth',
    'repositories',
    'repository',
    'security',
    'python',
    'javascript',
    'java',
    'golang',
    'rust',
    'ruby',
    'swift',
    'kotlin',
    'php',
    'html',
    'css',
    'node.js',
    'nodejs',
    'nextjs',
    'vue',
    'angular',
    'svelte',
    'solidjs',
    'django',
    'flask',
    'fastapi',
    'express',
    'nestjs',
    'postgres',
    'mongodb',
    'webpack',
    'vite',
    'npm',
    'git',
    'cli',
    'json',
    'yaml',
    'regex',
  ],

  simpleIndicators: [
    'what is',
    'define',
    'translate',
    'thanks',
    'thank you',
    'yes',
    'no',
    'ok',
    'okay',
    'sure',
    'got it',
    'hi',
    'hello',
    'hey',
    'bye',
    'goodbye',
    'how are you',
    'good morning',
    'good night',
    'please',
    'help',
    'what time',
    'where is',
    'who is',
  ],

  multiStep: [
    'first',
    'then',
    'after that',
    'finally',
    'step 1',
    'step 2',
    'step 3',
    'next',
    'subsequently',
    'once you',
    'followed by',
    'in sequence',
    'phase 1',
    'phase 2',
    'stage 1',
    'stage 2',
    'workflow',
    'pipeline',
  ],

  creative: [
    'story',
    'poem',
    'creative',
    'brainstorm',
    'imagine',
    'fiction',
    'narrative',
    'character',
    'plot',
    'dialogue',
    'write a song',
    'compose',
    'artistic',
    'metaphor',
    'allegory',
  ],

  questionComplexity: [
    'how does x relate to y',
    'what are the implications',
    'why would',
    'what happens if',
    'under what conditions',
    'how would you approach',
    'what is the relationship between',
  ],

  imperativeVerbs: [
    'build',
    'create',
    'update',
    'deploy',
    'send',
    'check',
    'run',
    'install',
    'configure',
    'set up',
    'launch',
    'publish',
    'submit',
    'execute',
    'start',
    'stop',
    'restart',
    'delete',
    'remove',
    'review',
    'optimize',
    'scan',
  ],

  outputFormat: [
    'as json',
    'in json',
    'as yaml',
    'in yaml',
    'as csv',
    'markdown',
    'as a table',
    'in a table',
    'as xml',
    'formatted as',
    'output as',
    'return as',
    'in the format',
  ],

  domainSpecificity: [
    'p-value',
    'confidence interval',
    'regression',
    'hipaa',
    'gdpr',
    'sec filing',
    'tort',
    'liability',
    'fiduciary',
    'amortization',
    'eigenvalue',
    'fourier transform',
    'bayesian',
    'posterior',
    'genome',
    'phenotype',
    'pharmacokinetics',
    'distribution',
    'probability',
    'statistics',
    'calculate',
  ],

  agenticTasks: [
    'triage',
    'audit',
    'investigate',
    'monitor',
    'orchestrate',
    'coordinate',
    'schedule',
    'prioritize',
    'delegate',
    'batch process',
    'scan all',
    'check all',
    'review all',
    'update all',
    'migrate',
    'remediation',
  ],

  relay: [
    'forward to',
    'escalate',
    'transfer to',
    'pass along',
    'relay',
    'just say',
    'tell them',
    'send this to',
    'notify',
    'ping',
    'acknowledge',
    'confirm receipt',
    'mark as read',
  ],
};
