export const DATA_ANALYSIS_KEYWORDS = [
  'csv',
  'dataframe',
  'pandas',
  'numpy',
  'chart',
  'plot',
  'visualization',
  'aggregate',
  'pivot',
  'correlation',
  'data analysis',
  'dataset',
  'spreadsheet',
  'histogram',
  'scatter plot',
  'heatmap',
  'dashboard',
  'metric',
  'metrics',
  'kpi',
  'funnel',
  'cohort',
  'segment',
  'median',
  'percentile',
  'variance',
  'z-score',
  'chi-square',
  'anova',
  'f-statistic',
  'covariance',
  'interquartile',
  'geometric mean',
  'trend',
  'forecast',
  'time series',
  'seasonal',
  'demographic',
  'survey',
  'sankey',
  'treemap',
  'waterfall chart',
  'pareto',
  'roi',
  'churn',
  'retention',
  'attrition',
  'burn rate',
  'conversion rate',
  'engagement',
  'customer lifetime value',
  'growth rate',
  'analyze',
  'compute',
  'visualize',
];
