export const EMAIL_MANAGEMENT_KEYWORDS = [
  'email',
  'inbox',
  'reply to',
  'forward email',
  'draft email',
  'compose email',
  'subject line',
  'newsletter',
  'outreach',
  'follow up',
  'mail merge',
  'unsubscribe',
  'cold email',
  'email template',
  'cc',
  'bcc',
  'attachment',
  'signature',
  'gmail',
  'outlook',
  'superhuman',
  'spark mail',
  'shortwave',
  'mailchimp',
  'sendgrid',
  'resend',
  'drip campaign',
];
