/**
 * Keywords that signal a "private document conversation" — the user is asking
 * the model to read, summarize, analyze, or act on documents that contain
 * sensitive / regulated data (medical records, contracts, legal briefs, etc.).
 *
 * When these keywords are detected, Manifest's specificity router can pin the
 * request to a privacy-preserving provider such as Privatemode (confidential
 * computing) instead of the default tier.
 *
 * This dimension has weight 0 in the complexity scorer (see scoring/config.ts)
 * — it is only consumed by specificity detection, not tier selection.
 *
 * False-positive care: standalone words like "contract" / "phi" can appear in
 * non-private coding contexts, so they are written as multi-word phrases
 * whenever possible. Only standalone terms that unambiguously signal private
 * data are kept as bare words.
 */
export const PRIVATE_DOCS_KEYWORDS = [
  // ── Regulatory / compliance terms ──
  'hipaa',
  'hipaa-compliant',
  'gdpr',
  'gdpr-compliant',
  'ccpa',
  'pdpa',
  'sox',
  'sarbanes-oxley',
  'personal data',
  'sensitive data',
  'personal information',
  'protected health information',
  'phi',
  'pii',
  'confidential',
  'privileged communication',
  'attorney-client privilege',
  'work product privilege',
  'attorney work product',
  'medical record',
  'patient record',
  'patient information',
  'patient file',
  'clinical note',
  'clinical record',
  'prescription',
  'diagnosis',
  'treatment plan',
  'health record',
  'healthcare data',
  'health data',
  'medical history',
  'medical records',
  'health records',
  'patient medical records',
  'patient medical history',

  // ── Document types that are typically sensitive ──
  'nda',
  'non-disclosure agreement',
  'confidentiality agreement',
  'confidential agreement',
  'master service agreement',
  'msa',
  'service agreement',
  'client agreement',
  'employment agreement',
  'settlement agreement',
  'legal brief',
  'brief filed',
  'motion to dismiss',
  'discovery document',
  'discovery document set',
  'discovery documents',
  'deposition transcript',
  'witness statement',
  'testimony',
  'insurance claim',
  'claims processing',
  'medical claim',
  'benefits claim',
  'financial statement',
  'financial statements',
  'audit trail',
  'audit log',
  'tax return',
  'tax document',
  'my tax return',
  'file my taxes',
  'irs document',
  'irs notice',
  'irs letter',
  'pay stub',
  'paycheck stub',
  'payroll record',
  'payroll records',
  'w2 form',
  'w-2 form',
  'my w-2',
  'my w2',
  'w-2 withholding',
  'w2 withholding',
  '1099 form',
  '1099 income',
  '1099 statement',
  'my 1099',
  '1099 withholding',
  '1099 tax',
  'payroll data',
  'my bank statement',
  'brokerage statement',
  'investment statement',
  'mortgage statement',
  'tax statement',
  'credit report',
  'credit score report',
  'background check',
  'security clearance',
  'performance review',
  'disciplinary action',
  'termination letter',
  'nda signed',

  // ── Financial account / retirement documents ──
  'my 401k',
  '401k statement',
  '401 k statement',
  '401(k) statement',
  'my ira',
  'ira statement',
  'roth ira statement',
  'traditional ira statement',
  'my roth ira',
  'my hsa',
  'hsa statement',
  'hsa account',
  'my fsa',
  'fsa statement',
  'fsa account',
  '529 plan statement',
  '529 savings statement',
  'my 529',
  '529 statement',
  '529 contribution',
  'brokerage account statement',
  'investment account statement',
  'retirement account statement',
  'pension statement',
  'pension plan document',

  // ── Document actions on private content ──
  'summarize this document',
  'summarize the document',
  'review this document',
  'review the document',
  'read this document',
  'read the document',
  'analyze this document',
  'analyze the document',
  'parse this document',
  'extract from this document',
  'redact this document',
  'redact the document',
  'anonymize this document',
  'de-identify this document',
  'deidentify this document',
  'review this confidential',
  'read this confidential',
  'read this privileged',
  'summarize this confidential',
  'summarize this privileged',
  'process this document securely',
  'keep this confidential',
  'handle this securely',
  'process with encryption',
  'confidential compute',
  'confidential processing',

  // ── Document conversation framing ──
  'private document conversation',
  'private doc conversation',
  'sensitive document conversation',
  'confidential conversation',
  'secure conversation',
  'encrypted conversation',
  'end-to-end encrypted',
  'confidential computing',
  'privatemode',
  'private mode',
  'secure ai',
  'encrypted ai',
  'verifiable compute',
  'remote attestation',
  'confidential vm',
  'confidential container',

  // ── Regulated industry document contexts ──
  'patient data',
  'client data',
  'customer data',
  'protected data',
  'regulated data',
  'compliance document',
  'regulatory document',
  'regulatory filing',
  'regulatory report',
  'soc 2',
  'soc 1',
  'soc 3',
  'soc2',
  'legal document',
  'medical document',
  'healthcare document',
  'health document',
  'medical files',
  'health files',
  'financial document',
  'payroll document',
  'hr document',
  'hr record',
  'employee record',
  'employee file',
  'customer record',
  'client file',
  'medical file',
  'confidential file',
  'privileged file',
  'sensitive file',
  'regulated file',
];
