export const SOCIAL_MEDIA_KEYWORDS = [
  'tweet',
  'post',
  'caption',
  'hashtag',
  'instagram',
  'tiktok',
  'linkedin',
  'facebook',
  'twitter',
  'social media',
  'followers',
  'engagement',
  'viral',
  'repost',
  'thread',
  'schedule post',
  'content calendar',
  'influencer',
  'audience',
  'reach',
  'hootsuite',
  'buffer',
  'sprout social',
  'later',
  'feedhive',
  'brand24',
  'bluesky',
  'threads',
  'youtube shorts',
  'reel',
  'story',
  'carousel',
  'bio',
  'giveaway',
  'brand',
  'community',
  'content',
  'poll',
  'campaign',
  'spotlight',
  'milestone',
  'evergreen',
  'announcement',
  'DM',
  'social ad',
  'trending',
  'hook',
  'pin',
  'pinterest',
  'write a post',
  'draft a post',
  'create a post',
  'social strategy',
  'social content',
  'new feature',
  'testimonial',
  'user generated',
  'cross platform',
  'social listening',
  'social coverage',
  'social report',
  'write copy',
  'engagement rate',
  'share of voice',
];
