export const TRADING_KEYWORDS = [
  'buy',
  'sell',
  'trade',
  'stock',
  'crypto',
  'bitcoin',
  'ethereum',
  'forex',
  'portfolio',
  'market',
  'ticker',
  'candle',
  'bullish',
  'bearish',
  'stop loss',
  'take profit',
  'leverage',
  'margin',
  'order book',
  'moving average',
  'rsi',
  'macd',
  'support and resistance',
  'breakout',
  'dividend',
  'hedge',
  'kalshi',
  'polymarket',
  'robinhood',
  'interactive brokers',
  'webull',
  'tradingview',
  'coinbase',
  'kraken',
  'binance',
  'bitget',
  'prediction market',
  'event contract',
  'solana',
  'defi',
  'shares',
  'options',
  'futures',
  'etf',
  'price',
  'earnings',
  'yield',
  'pe ratio',
  'volatility',
  'vix',
  'fibonacci',
  'position',
  'entry',
  'short interest',
  'staking',
  'arbitrage',
  'sharpe ratio',
  'alpha',
  'beta',
  'drawdown',
  'swing trade',
  'day trading',
  'limit order',
  'market order',
  'fomc',
  'cpi',
  'sec',
  'insider trading',
  'commodity',
  'bond',
  'fund',
  'exchange',
  'spread',
  'order',
  'position size',
  'risk reward',
  'dark pool',
  'kelly criterion',
  'momentum',
  'sector rotation',
  'growth stock',
  'economic calendar',
  'stock price',
  'current price',
  'best entry',
  'place a',
  'place an order',
  'check my portfolio',
  'top gaining',
  'pre market',
  'after hours',
  'earnings call',
  'earnings date',
  'trading journal',
  'risk reward ratio',
  'position sizing',
  'copy trading',
  'paper trading',
  'candlestick',
  'oversold',
  'overbought',
  'resistance level',
  'support level',
  'price action',
  'moving average crossover',
  'death cross',
  'golden cross',
  'fear and greed',
  'funding rate',
  'put call',
  'implied volatility',
  'options chain',
  '52 week',
  'all time high',
  'market cap',
  'dollar cost averaging',
  'compound interest',
  'total return',
  'annual return',
  'expense ratio',
  'analyze the chart',
  'analyze the pattern',
  'analyze the trend',
  'analyze the market',
  'technical analysis',
  'fundamental analysis',
  'price target',
  'market sentiment',
  'whale activity',
  'accumulation',
  'distribution',
  'cup and handle',
  'head and shoulders',
  'double bottom',
  'double top',
  'wedge pattern',
  'flag pattern',
  'pennant',
  'volume profile',
  'retracement',
];
