export const VIDEO_GENERATION_KEYWORDS = [
  'generate video',
  'create video',
  'animation',
  'animate',
  'video edit',
  'clip',
  'footage',
  'motion graphics',
  'timelapse',
  'time lapse',
  'transition',
  'subtitle',
  'storyboard',
  'keyframe',
  'render video',
  'sora',
  'runway',
  'kling',
  'pika',
  'veo',
  'synthesia',
  'heygen',
  'capcut',
  'opusclip',
  'higgsfield',
  'text to video',
  'image to video',
  'video',
  'reel',
  'shorts',
  'trailer',
  'montage',
  'voiceover',
  'lip sync',
  'slow motion',
  'color grading',
  'green screen',
  'cinematic',
  'looping',
  'captions',
  'speed ramp',
  'stop motion',
  'explainer',
  'promo',
  'testimonial',
  'tutorial video',
  'demo video',
  'film',
  'recording',
  'webinar',
  'camera',
  'scene',
  'frame',
  'make a video',
  'create a video',
  'produce a video',
  'generate a video',
  'video for',
  'youtube',
  'tiktok video',
  'instagram reel',
  'video content',
  'video template',
  'video presentation',
  'video portfolio',
  'video greeting',
  'video resume',
  'screen recording',
  'video loop',
  'video ad',
  'video post',
  'video story',
];
