import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Soft-delete support for agents (#1765).
 *
 * Replaces the (tenant_id, name) unique constraint with a partial unique
 * index that only covers live rows, so a deleted agent's slug can be reused
 * by a fresh agent.
 */
export class AddAgentSoftDelete1782200000000 implements MigrationInterface {
  name = 'AddAgentSoftDelete1782200000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "agents" ADD COLUMN "deleted_at" TIMESTAMP NULL`);

    // Drop the existing unique index on (tenant_id, name). The name was
    // generated by TypeORM in the InitialSchema migration; resolve it via
    // pg_indexes to stay portable across installs.
    const rows: { indexname: string }[] = await queryRunner.query(
      `SELECT indexname FROM pg_indexes
       WHERE tablename = 'agents' AND indexdef LIKE 'CREATE UNIQUE INDEX%(tenant_id, name)'`,
    );
    for (const row of rows) {
      await queryRunner.query(`DROP INDEX IF EXISTS "${row.indexname}"`);
    }

    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_agents_tenant_name_live"
         ON "agents" ("tenant_id", "name")
       WHERE "deleted_at" IS NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "UQ_agents_tenant_name_live"`);

    // After recreate flows, multiple rows can share (tenant_id, name). The
    // full unique index can't be restored as-is. Mangle the soft-deleted
    // slugs with the row id so the rows survive (FKs in agent_messages,
    // tier_assignments, etc. stay intact) without colliding with the live
    // slug. Anyone re-applying the migration can pick the rows up by
    // deleted_at; since the column is being dropped, that means no one — but
    // the audit data is preserved if someone restores the schema later.
    await queryRunner.query(
      `UPDATE "agents"
          SET "name" = "name" || '__deleted_' || "id"
        WHERE "deleted_at" IS NOT NULL`,
    );

    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_agents_tenant_name" ON "agents" ("tenant_id", "name")`,
    );
    await queryRunner.query(`ALTER TABLE "agents" DROP COLUMN "deleted_at"`);
  }
}
