openapi: 3.0.3
info:
  title: Email API
  description: |
    Internal API for email operations in the Generator application.
    These endpoints are primarily for development/testing purposes.
    In production, emails are triggered by internal services, not HTTP calls.
  version: 1.0.0
  contact:
    name: Generator Team

servers:
  - url: http://localhost:3847/api
    description: Development server

paths:
  /email/preview/{template}:
    get:
      summary: Preview email template
      description: |
        Renders an email template with provided props and returns HTML.
        Used for development preview without sending.
      operationId: previewEmailTemplate
      tags:
        - Email
      parameters:
        - name: template
          in: path
          required: true
          description: Template type to preview
          schema:
            $ref: '#/components/schemas/EmailTemplateType'
        - name: userName
          in: query
          description: User name (for password-reset)
          schema:
            type: string
            example: "John Doe"
        - name: resetLink
          in: query
          description: Password reset link (for password-reset)
          schema:
            type: string
            format: uri
            example: "https://app.example.com/reset?token=abc123"
        - name: inviterName
          in: query
          description: Inviter's name (for invitation)
          schema:
            type: string
            example: "Jane Smith"
        - name: appName
          in: query
          description: Application name (for invitation)
          schema:
            type: string
            example: "My Awesome App"
        - name: appLink
          in: query
          description: Application link (for invitation)
          schema:
            type: string
            format: uri
            example: "https://app.example.com/invite?code=xyz789"
      responses:
        '200':
          description: Rendered HTML email
          content:
            text/html:
              schema:
                type: string
                description: Complete HTML email content
        '400':
          description: Invalid template or missing required props
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Template not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /email/templates:
    get:
      summary: List available templates
      description: Returns list of available email template types.
      operationId: listEmailTemplates
      tags:
        - Email
      responses:
        '200':
          description: List of template types
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      $ref: '#/components/schemas/EmailTemplateType'
                example:
                  templates:
                    - password-reset
                    - invitation

  /email/send:
    post:
      summary: Send email (development only)
      description: |
        Sends an email using the configured provider.
        **WARNING**: This endpoint should be disabled or protected in production.
        In production, emails are triggered by internal service calls.
      operationId: sendEmail
      tags:
        - Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailRequest'
      responses:
        '200':
          description: Email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailSendResult'
        '400':
          description: Invalid request (bad email format, missing props)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Email provider error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /email/config:
    get:
      summary: Get email configuration status
      description: |
        Returns current email configuration status.
        Sensitive values (API keys) are masked.
      operationId: getEmailConfig
      tags:
        - Email
      responses:
        '200':
          description: Email configuration status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailConfigStatus'

components:
  schemas:
    EmailTemplateType:
      type: string
      enum:
        - password-reset
        - invitation
      description: Available email template types

    SendEmailRequest:
      type: object
      required:
        - to
        - template
        - props
      properties:
        to:
          type: string
          format: email
          description: Recipient email address
          example: "user@example.com"
        template:
          $ref: '#/components/schemas/EmailTemplateType'
        props:
          type: object
          description: Template-specific properties
          additionalProperties: true
          example:
            userName: "John Doe"
            resetLink: "https://app.example.com/reset?token=abc123"
        replyTo:
          type: string
          format: email
          description: Optional reply-to address

    EmailSendResult:
      type: object
      required:
        - success
        - timestamp
      properties:
        success:
          type: boolean
          description: Whether the email was sent successfully
        messageId:
          type: string
          description: Provider-assigned message ID
          example: "20260110123456.abc123@mg.example.com"
        error:
          type: string
          description: Error message if send failed
        timestamp:
          type: string
          format: date-time
          description: When the send was attempted

    EmailConfigStatus:
      type: object
      properties:
        provider:
          type: string
          description: Currently configured provider
          example: "mailgun"
        configured:
          type: boolean
          description: Whether provider is properly configured
        from:
          type: string
          description: Default sender address
          example: "noreply@example.com"
        domain:
          type: string
          description: Sending domain (if applicable)
          example: "mg.example.com"

    ErrorResponse:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
          description: HTTP status code
        message:
          type: string
          description: Error message
        error:
          type: string
          description: Error type

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token (when auth is implemented post-POC)

tags:
  - name: Email
    description: Email operations and template management
