# Node Types API Contract
# Feature: 001-ui-selection
# Date: 2026-01-07

openapi: 3.0.3
info:
  title: Node Types API
  description: API for retrieving available node types including the new StatCard UI
  version: 1.0.0

paths:
  /api/node-types:
    get:
      summary: List all available node types
      description: Returns all built-in node types including the new StatCard UI component
      operationId: getNodeTypes
      responses:
        '200':
          description: Successfully retrieved node types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeTypeInfo'
              example:
                - name: StatCard
                  displayName: Stat Card
                  icon: bar-chart-3
                  group: [ui, display, stats]
                  category: interface
                  description: Display statistical metrics with trend indicators
                  inputs: [main]
                  outputs: []
                  defaultParameters:
                    layoutTemplate: stat-card
                  inputSchema:
                    type: object
                    properties:
                      stats:
                        type: array
                  outputSchema: null
                  hasDynamicInputSchema: false
                  hasDynamicOutputSchema: false

  /api/node-types/{name}:
    get:
      summary: Get a specific node type by name
      operationId: getNodeTypeByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          example: StatCard
      responses:
        '200':
          description: Successfully retrieved node type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeTypeInfo'
        '404':
          description: Node type not found

components:
  schemas:
    NodeTypeInfo:
      type: object
      required:
        - name
        - displayName
        - icon
        - group
        - category
        - description
        - inputs
        - outputs
        - defaultParameters
        - hasDynamicInputSchema
        - hasDynamicOutputSchema
      properties:
        name:
          type: string
          description: Internal type name
          example: StatCard
        displayName:
          type: string
          description: Human-readable display name
          example: Stat Card
        icon:
          type: string
          description: Lucide icon name
          example: bar-chart-3
        group:
          type: array
          items:
            type: string
          description: Category tags for grouping
          example: [ui, display, stats]
        category:
          type: string
          enum: [trigger, interface, action, return]
          description: Node type category
          example: interface
        description:
          type: string
          description: What the node does
          example: Display statistical metrics with trend indicators
        inputs:
          type: array
          items:
            type: string
          description: Input handle types
          example: [main]
        outputs:
          type: array
          items:
            type: string
          description: Output handle types (empty for read-only nodes)
          example: []
        defaultParameters:
          type: object
          additionalProperties: true
          description: Default parameter values
          example:
            layoutTemplate: stat-card
        inputSchema:
          $ref: '#/components/schemas/JSONSchema'
          nullable: true
        outputSchema:
          $ref: '#/components/schemas/JSONSchema'
          nullable: true
        hasDynamicInputSchema:
          type: boolean
          description: Whether input schema is computed dynamically
        hasDynamicOutputSchema:
          type: boolean
          description: Whether output schema is computed dynamically

    JSONSchema:
      type: object
      description: JSON Schema definition
      additionalProperties: true

    StatCardData:
      type: object
      required:
        - label
        - value
      properties:
        label:
          type: string
          minLength: 1
          description: Metric name
          example: Sales
        value:
          oneOf:
            - type: string
            - type: number
          description: Display value
          example: "$12,543"
        change:
          type: number
          description: Percentage change
          example: 12.5
        changeLabel:
          type: string
          description: Change description
          example: vs last month
        trend:
          type: string
          enum: [up, down, neutral]
          description: Trend direction
          example: up

    StatsInputData:
      type: object
      required:
        - stats
      properties:
        stats:
          type: array
          items:
            $ref: '#/components/schemas/StatCardData'
          description: Array of statistics to display

    LayoutTemplate:
      type: string
      enum: [stat-card]
      description: Available layout templates (table and post-list removed)

    LayoutTemplateConfig:
      type: object
      required:
        - manifestBlock
        - installCommand
        - useCase
        - actions
      properties:
        manifestBlock:
          type: string
          description: Manifest UI block identifier
          example: "@manifest/stats"
        installCommand:
          type: string
          description: Command to install the component
          example: "npx shadcn@latest add @manifest/stats"
        useCase:
          type: string
          description: Primary use case description
          example: "KPIs, dashboard stats, metrics overview"
        actions:
          type: array
          items:
            $ref: '#/components/schemas/LayoutAction'
          description: Available actions (empty for read-only)

    LayoutAction:
      type: object
      required:
        - name
        - label
        - description
      properties:
        name:
          type: string
          description: Action identifier
        label:
          type: string
          description: Display label
        description:
          type: string
          description: Action description
