openapi: 3.0.3
info:
  title: App Detail Improvements API
  description: API contracts for app icon upload functionality
  version: 1.0.0

paths:
  /api/apps/{appId}/icon:
    post:
      summary: Upload app icon
      description: |
        Upload a custom icon for an app. The icon must be a square image
        at least 128x128 pixels in PNG, JPG, GIF, or WebP format.
      operationId: uploadAppIcon
      tags:
        - Apps
      parameters:
        - name: appId
          in: path
          required: true
          description: The app's unique identifier
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - icon
              properties:
                icon:
                  type: string
                  format: binary
                  description: Icon image file (PNG, JPG, GIF, or WebP)
      responses:
        '200':
          description: Icon uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IconUploadResponse'
        '400':
          description: Invalid file (wrong type, too large, wrong dimensions)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: App not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/apps:
    post:
      summary: Create a new app (with default icon)
      description: |
        Creates a new app. A random default icon from 8 available options
        is automatically assigned.
      operationId: createApp
      tags:
        - Apps
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAppRequest'
      responses:
        '201':
          description: App created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'

components:
  schemas:
    App:
      type: object
      required:
        - id
        - name
        - slug
        - themeVariables
        - status
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500
          nullable: true
        slug:
          type: string
        themeVariables:
          type: object
          description: Theme configuration
        status:
          type: string
          enum: [draft, published]
        logoUrl:
          type: string
          nullable: true
          description: URL to the app icon (default or custom)
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateAppRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500
        themeVariables:
          type: object
          description: Optional theme overrides

    IconUploadResponse:
      type: object
      required:
        - iconUrl
      properties:
        iconUrl:
          type: string
          description: URL to the uploaded icon

    ErrorResponse:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string
